### ISSUE TITLE
Leverage metavariable matching in sgrep-lint

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#405] opened 2020-04-08 16:57 UTC
#403 added metavariable IDs to track variables between patterns. Let's use this in sgrep-lint.

**Comment by brendongo** [comment] 2020-04-09 23:31
I'm assuming this is referring to https://github.com/returntocorp/sgrep/pull/403/files

**Comment by DrewDennison** [comment] 2020-04-16 05:53
#403 is merged so this is unblocked

**Comment by aryx** [comment] 2020-04-16 13:26
See https://github.com/returntocorp/sgrep/issues/434 as an example which require this feature.

**Comment by dlukeomalley** [comment] 2020-05-01 17:12
Is this a duplicate of #176?

**Closed as completed** 2020-05-03 03:37 UTC
