### ISSUE TITLE
SARIF out put failing in github actions

### ISSUE THREAD

**Issue by romichg** [semgrep/semgrep#4191] opened 2021-11-01 14:55 UTC
**Describe the bug**
When using github actions to run Semgrep with the option to produce SARIF file, Semgrep fails

**To Reproduce**
Enable SARIF generation by passing 
` generateSarif: "1"` in semgrep.yml file

**Expected behavior**
Run to complete normally with SARIF file generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/1326120/139691664-bede6859-ca89-42a9-9de7-1f9172dfafeb.png)

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Github Actions

**Comment by roisec** [comment] 2021-11-08 22:12
+1

**Comment by TinMarkovic** [comment] 2021-11-09 10:49
I am unable to reproduce as of now. 

This semgrep run went through without issues even with `generateSarif` configured: https://github.com/TinMarkovic/django.nV/runs/4150815248?check_suite_focus=true

Can you give me more tips to help me reproduce? Specifics of your repo, any kind of pattern you might consider an important difference than the test repo I use?

**Comment by brendongo** [comment] 2022-04-21 02:09
Closing since we are unable to reproduce

**Closed as completed by brendongo** 2022-04-21 02:09 UTC
Labels: priority:medium, feature:cli-output
