### ISSUE TITLE
JS somehow parses lua

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4157] opened 2021-10-27 02:47 UTC
**Describe the bug**
[This issue on semgrep-rules](https://github.com/returntocorp/semgrep-rules/issues/1489) shows a strange circumstance where `javascript.lang.correctness.useless-eqeq` somehow parses and reports this finding on a lua file.

Notably, this only works when the `lua` file is explicitly listed, so this isn't an issue with default language extensions.

**To Reproduce**
Strangely, this doesn't work on semgrep.dev: https://semgrep.dev/s/Z4En

However, if I use this on a local file, it will parse and report the finding.

```lua
local name
if name == nil or name == "" then -- semgrep causes java.lang.correctness.eqeq.eqeq exception  here, it should not
end
```

```yaml
rules:
- id: zzzz
  pattern: $X == $X
  message: Semgrep found a match
  languages: [js]
  severity: INFO
```

```console
➜  lua semgrep -v -f something.yaml something.lua
running 1 rules from 1 config something.yaml_0
Running 1 rules...
rules:
- zzzz
Semgrep Core WARN - Syntax error: When running zzzz on something.lua: `local` was unexpected
something.lua
severity:info rule:zzzz: Semgrep found a match
2:if name == nil or name == "" then -- semgrep causes java.lang.correctness.eqeq.eqeq exception  here, it should not
--------------------------------------------------------------------------------
2:if name == nil or name == "" then -- semgrep causes java.lang.correctness.eqeq.eqeq exception  here, it should not
ran 1 rules on 1 files: 2 findings
found problems analyzing 1 file; run with --verbose for details or run with --strict to exit
non-zero if any file cannot be analyzed cleanly
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False

```

**Expected behavior**
Maybe this is caused by some kind of partial parsing? In any case, I would've expected JS to fail on lua.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed
- [x] P3: strange edge case 😄 

**Environment**
Semgrep 0.70.0

**Comment by underyx** [comment] 2022-03-11 00:14
I cannot reproduce with 0.84 so closing. @minusworld could you confirm on your end as well and reopen if the issue is still present for you? I didn't understand you your command was `$ lua semgrep -v [...]` so I just ran `$ semgrep -v [...]`.

<img width="1261" alt="CleanShot 2022-03-10 at 16 13 08@2x" src="https://user-images.githubusercontent.com/1060436/157777032-85114100-a8ef-488a-9a57-ab604f02d2cf.png">

**Closed as completed** 2022-03-11 00:14 UTC
Labels: bug, priority:low, exotic, lang:lua
