### ISSUE TITLE
Semgrep.dev playground converts language to python

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4569] opened 2022-01-25 17:06 UTC
**Describe the bug**
When you open a registry item such as https://semgrep.dev/p/secrets in the playground it converts the value to python and it errors out not running

**To Reproduce**
Open Visit https://semgrep.dev/editor?registry=generic.secrets.security.detected-amazon-mws-auth-token.detected-amazon-mws-auth-token 

See error:
```
{"code":3,"level":"warn","message":"Semgrep Core WARN - Syntax error in file target.py:2\n\t`.00` was unexpected","path":"target.py","type":"Syntax error"}
```

**Expected behavior**
Should use the language specified in the advanced config e.g. generic or regex

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Environment**
Visit https://semgrep.dev/editor?registry=generic.secrets.security.detected-amazon-mws-auth-token.detected-amazon-mws-auth-token

**Comment by annikalee** [comment] 2022-11-09 20:24
I am unable to replicate this anymore so I'm closing as cannot reproduce. Let me know if this is still an issue!

**Closed as completed by annikalee** 2022-11-09 20:24 UTC
Labels: bug, priority:medium, cannot-reproduce
