### ISSUE TITLE
Parse ?? operator in js

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1518] opened 2020-08-17 16:51 UTC
**Describe the bug**
Semgrep unable to parse ?? operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**To Reproduce**
 https://semgrep.dev/1L8G/

**Expected behavior**
See doc link above

**Comment by mjambon** [comment] 2020-08-17 17:36
This will be supported when we switch to the tree-sitter implementation.

**Comment by nbrahms** [comment] 2020-08-21 00:15
Duplicate of #1351

**Closed as completed by nbrahms** 2020-08-21 00:15 UTC
Labels: bug, lang:javascript

**Comment by aryx** [comment] 2020-08-29 15:55
This works now! no more parse error.
