### ISSUE TITLE
Error: semgrep-core exited with unexpected output

### ISSUE THREAD

**Issue by tuhaolam** [semgrep/semgrep#9975] opened 2024-03-20 13:44 UTC
**Describe the bug**
semgrep-core exited with unexpected output.

**To Reproduce**
````
semgrep --metrics off --config=xxx ~/dev/online_log/gunicorn_ctl.py


┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 1 file tracked by git with 1 Code rule:
  Scanning 1 file.
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
[ERROR] Error while running rules:
                    You are seeing this because the engine was killed.

                    The most common reason this happens is because it used too much memory.
                    If your repo is large (~10k files or more), you have three options:
                    1. Increase the amount of memory available to semgrep
                    2. Reduce the number of jobs semgrep runs with via `-j <jobs>`. We
                        recommend using 1 job if you are running out of memory.
                    3. Scan the repo in parts (contact us for help)

                    Otherwise, it is likely that semgrep is hitting the limit on only some
                    files. In this case, you can try to set the limit on the amount of memory
                    semgrep can use on each file with `--max-memory <memory>`. We recommend
                    lowering this to a limit 70% of the available memory. For CI runs with
                    interfile analysis, the default max-memory is 5000MB. Without, the default
                    is unlimited.

                    The last thing you can try if none of these work is to raise the stack
                    limit with `ulimit -s <limit>`.

                    If you have tried all these steps and still are seeing this error, please
                    contact us.

                       Error: semgrep-core exited with unexpected output
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
on cvm.
```
semgrep --version
1.27.0

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

Versions prior to 1.31.0 are no longer supported by Semgrep.dev, please upgrade.
```

**Use case**
What will fixing this bug enable for you?

**Comment by kopecs** [comment] 2024-03-20 17:46
The output from running with `--debug` would be useful, but I suspect this is the root cause as https://github.com/semgrep/semgrep/issues/9974 and `semgrep-core` is exiting for the same reason as there.

Edit: or perhaps not, given the version difference between here and there, but 1.27.0 is no longer supported.

**Comment by ievans** [comment] 2024-03-20 22:14
Going to close out as this bug was likely fixed in a later version and the https://github.com/semgrep/semgrep/issues/9974 is tracking (but feel free to re-open)

**Closed as completed by ievans** 2024-03-20 22:14 UTC
Labels: bug
