### ISSUE TITLE
extend AST to include comments

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#630] opened 2020-04-30 17:44 UTC
If I want to look for all `//eslint-disable` comments in my codebase, I would like to use semgrep for this. Maybe I can use #629 ?

**Comment by DrewDennison** [comment] 2020-04-30 17:45
@ievans and @aryx for thoughts on how much work this is

**Comment by ievans** [comment] 2020-04-30 19:10
I think TBH it would be ideal to use #629 for this.

**Comment by aryx** [comment] 2020-04-30 20:56
I agree with isaac. Note that pfff actually keep comments. Each parsing function in pfff returns both an AST and a list of tokens, and this list of tokens actually contains the comments (I needed that for codemap to be able to colorize files, in which case I need also to colorize the comments).
There are a few functions in pfff/h_program-lang/comment_code.ml to access the comments after or before AST elements, but it's not plugged in semgrep right now. It could, but pattern-regex seems simpler.

**Comment by aryx** [comment] 2020-04-30 20:57
So the issue is already fixed; comments are there if you want them. The question is how to use that in semgrep.

**Comment by ievans** [comment] 2020-04-30 21:34
Until we hear more specific asks or cases where #629 wouldn't work, I'm going to close this in favor of #629 @DrewDennison

**Closed as completed by ievans** 2020-04-30 21:34 UTC
Labels: wontfix
