### ISSUE TITLE
semgrep-core linked to homebrew libpcre.1.dylib

### ISSUE THREAD

**Issue by lundberg** [semgrep/semgrep#6026] opened 2022-09-02 06:57 UTC
**Describe the bug**
Running `semgrep` complains about `libpcre.1.dylib` not loaded. Looks to be same issue as #2624, but for macOS.

**To Reproduce**
```sh
# Install
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install semgrep

# Run
$ ./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
dyld[24562]: Library not loaded: /opt/homebrew/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /private/tmp/test/.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
  Reason: tried: '/opt/homebrew/opt/pcre/lib/libpcre.1.dylib' (no such file), '/usr/local/lib/libpcre.1.dylib' (no such file), '/usr/lib/libpcre.1.dylib' (no such file)

# Verify shared libraries
$ otool -L ./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/opt/homebrew/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.13.0)
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
* Apple M2
* macOS Monterey

**Comment by r2c-demo** [comment] 2022-09-02 06:57
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1840/semgrep-core-linked-to-homebrew-libpcre1dylib. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment] 2022-09-02 13:57
@spencerdrak can you have a look? I think you recently had a fix regarding homebrew. Is it related?

**Comment by spencerdrak** [comment] 2022-09-02 14:06
Yep, I'll take a look. @lundberg thanks for reporting! I saw you opened PR #6027 - this definitely is incorrect, but our build process also ensures that the dynamic libraries are removed before each run, so I'm not sure that it'll solve the issue. We'll do some more digging.

(And by definitely incorrect, I mean that your PR fixes an incorrect line of code)

**Comment by spencerdrak** [comment] 2022-09-02 15:07
@lundberg was the `otool` command run on an M1 mac?

**Comment by spencerdrak** [comment] 2022-09-02 18:17
@lundberg we weren't able to reproduce this on either an M1 or X64 mac - can you provide any more info about the bug?

**Comment by lundberg** [comment] 2022-09-03 16:45
@spencerdrak I ran this on a clean Mac M2 without homebrew or commandline tools. I installed otool using nix package manager to check semgrep-core.

**Comment by TheErk** [comment] 2022-09-10 13:09
I have a similar issue on Mac M1.
I did install semgrep in a pristine venv using `pip install semgrep`, then running semgrep fails due to missing lib because
`/opt/homebrew/opt/pcre/lib/libpcre.1.dylib` wasn't found which is normal because I use [Mac Port](https://www.macports.org/) and not [Homebrew](https://brew.sh/) thus the proper pcre lib is installed at: `/opt/local/lib/libpcre.1.dylib`

I did:
`install_name_tool -change /opt/homebrew/opt/pcre/lib/libpcre.1.dylib /opt/local/lib/libpcre.1.dylib <venv_prefix>/lib/python3.9/site-packages/semgrep/bin/semgrep-core`

which then works as expected.
May be the pip installable semgrep module should check for missing/not found dynamic libraries?

NB: I did not install semgrep from Mac Ports because the port is outdated (https://ports.macports.org/port/semgrep/details/)

**Comment by sww** [comment] 2022-10-07 20:35
I also ran into this issue on a new M1 MacBook Pro.  In my case, `semgrep` was installed via pip, which did not install the `pcre` dependency (but `pcre` DOES get installed if you install `semgrep` via Homebrew). I think I've fixed in my PR https://github.com/returntocorp/semgrep/pull/6268.

**Closed as completed** 2022-10-11 10:51 UTC
Labels: priority:medium, devops
