### ISSUE TITLE
Presence/absence of statement terminator drastically changes match

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2137] opened 2020-11-30 22:47 UTC
**Describe the bug**
In this sandbox 1 (https://semgrep.dev/s/OkBe/) observe:
(a) there is no statement terminator on the pattern
(b) the expression is matched in the sample
<img width="375" alt="image" src="https://user-images.githubusercontent.com/6817500/100673510-69ab5580-3318-11eb-8db1-a52f782a42cf.png">

In this sandbox 2 (https://semgrep.dev/s/erwX/) observe:
(a) now there is a statement terminator added to the pattern
(b) the entire statement is matched
<img width="375" alt="image" src="https://user-images.githubusercontent.com/6817500/100673579-88115100-3318-11eb-89f2-dd6e7a876528.png">

Now here is where it really gets interesting: trying to place the `// nosem` is quite a challenge!
<img width="529" alt="image" src="https://user-images.githubusercontent.com/6817500/100674578-38cc2000-331a-11eb-9e58-c33b7642ec88.png">

**To Reproduce**
See above.

**Expected behavior**
For matching, sandbox 2 should either:
(a) return the same match as the first
(b) return no matches
Have not thought through which of these is ultimately correct.

For placing `// nosem`, seems like it should always be on the pattern not on the surrounding statement.

**Screenshots**
See above.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

The `// nosem` portion feels like a priority P1 (assuming you agree with my interpretations above, that is). It is possible you might come back and say this is by design, but it does seem counterintuitive

**Environment**
semgrep v 0.32.0

**Comment by minusworld** [comment] 2020-11-30 23:19
Thanks @msorens! @aryx - Do you know why this might be happening?

**Comment by aryx** [comment] 2020-12-01 15:37
It is important to understand that in programming languages like C/C++/Java/Javascript/... there are _expressions_ and _statements_. Those are 2 different things. Expressions can appear inside if conditions, in function call arguments, etc. Statements can not appear everywhere; they are sequence of operations (with ; as a separator/terminator) or special control flow constructs (if, while, etc.).

So, foo() and foo(); are 2 different beasts. When you write the pattern 'foo()', semgrep will visit every expressions and sub-expressions in your program and try to find a match. When you write the pattern 'foo();' in theory semgrep will visit every statements in your program and try to find a match. Note that 'foo();' is confusingly called an expression statement, but it is first a statement.

Now, many programmers don't really see the difference between foo() and foo();, and this is why semgrep internally when one looks for foo();  actually thinks that the user may also wanted to match a statement like a = foo();, or (this where we might have been wrong) wanted to match a statement like print(foo());

This is what happens here; when you wrote $EXPR.subscribe(...);  with a semicolon, we assume you want to find
an expression statement and we match it against many full statements and we magically accept it to match full statement where $EXPR.subscribe(...) is slightly nested inside the statement.

**Comment by aryx** [comment] 2020-12-01 15:38
This is an explanation on why the statement pattern match the whole statement, because that's how the engine works; when you write a statement in a pattern, we will visit every statement and match it against, and if there's a match, we say the (whole) statement matched.

**Comment by aryx** [comment] 2020-12-01 15:41
Note that when you look for foo();,  semgrep also accept to match return foo();, even though technically those are 2 different kinds
of statements. And again, semgrep will return a match to the full statement 'return foo();', not just the expression part foo().

**Comment by aryx** [comment] 2020-12-01 15:42
We could change that, but we may break many existing rules doing so.

**Comment by msorens** [comment] 2020-12-01 17:27
Thanks, @aryx. Yes, it is precisely because of the difference between expressions and statements that this is an issue. In fact, when you state "... we magically accept it to match full statement...", I am not sure that is desirable. Certainly "magic" implies unexpected behavior to some percentage of your users, as it did for me.

In fact, in this instance I meant to target an expression rather than a statement but I inadvertently included the semicolon. So I would have preferred no match, which would then have led me to examine my pattern more closely and find the errant semicolon I included. As it is, I instead was puzzled for some time over why my `// nosemgrep` clauses were not working. I was aware that `// nosemgrep` is supposed to be on the first line of a match, but at the time I was trying to figure out what happened I did not know what the whole match was; I only knew the `// nosemgrep` was not being honored. I tried on a whim moving it to the first line of the surrounding statement to see if that would trigger and it did. But I could see this as a point of frustration for some users.

Finally, the current behavior means there is no way to write a rule specifically targeting an expression vs. targeting a statement.

It may not be cost-effective to change this if, as you say, it could break many rules, but at a minimum, may I suggest this gets conspicuously documented?

**Comment by aryx** [comment] 2020-12-02 08:14
One issue is that for the case of a single pattern like foo();, maybe indeed we should not apply the magic, and maybe
give a warning to the user saying "you probably want to remove the semicolon", but the problem is when you use a more complex pattern like
foo();
...
bar();

and we like that this matches even code like foo();stuff(); return bar();  or even foo(); stuff(); print bar();


Without this magic, you will need to write
<... foo() ...>
...
<... bar() ...>

which is pretty ugly.

**Comment by msorens** [comment] 2020-12-02 15:57
Agreed about the ugliness 😁 and since I am still on the learning curve I certainly accept your judgment. I still think it would be useful to document in some fashion.

**Comment by ievans** [comment] 2020-12-05 03:09
Agreed that the documentation should definitely be updated to explain this in detail @msorens.

The choice to search for statements as _both_ expressions and statements was something that I pushed heavily for; the earliest versions of semgrep (sgrep :)) didn't do it. As @aryx said, since many of our users don't fully understand the difference between statements and expressions, making the engine try to follow a user's intuitive mental model is a design decision that (I think) benefits the novice user at the expense of some annoyance to the expert. Definitely willing to reconsider the decision though.

But I'm not actually sure that's necessary; I wonder if there's a simpler fix here that just narrows the reported semgrep range? I think the logic would be: if we've taken a statement and used it as an expression for the purposes of search, we still perform a narrowing after the transformed match to the smallest possible match? @aryx is that possible or am I missing something.

(Separately, we need to create a issue to track the story we have about specifying a subset of the match as the output)

**Comment by ievans** [comment] 2020-12-07 18:44
@msorens how would you feel if I closed this in favor of https://github.com/returntocorp/semgrep/issues/2199 and creating a section in the documentation talking about expression vs statement?

**Comment by msorens** [comment] 2020-12-07 21:33
That is certainly sufficient. Based on the thoughtful comments in this thread, I am not at all sure there should be any changes at this point other than documentation; you have definitely put more time into thinking about this than I have. 👍

**Comment by ievans** [comment] 2020-12-07 23:31
@msorens thanks for the quick reply, and I really appreciate your detailed original writeup. I'm going to close in favor of #2199 and I opened a PR to add some of @aryx 's comments to the documentation here: https://github.com/returntocorp/semgrep-docs/pull/61

**Closed as completed** 2020-12-07 23:31 UTC
Labels: bug, documentation, user:external, lang:javascript, semgrep-is-not-grep
