### ISSUE TITLE
Detecting absence of Java annotations

### ISSUE THREAD

**Issue by nightwatchcyber** [semgrep/semgrep#2320] opened 2020-12-31 14:13 UTC
**Describe the bug**
Trying to figure out how to detect the absence of a Java annotation when other annotations are used.

Here is one that detect the presence of "@RolesAllowed" within another one:
https://semgrep.dev/s/nightwatchcyber:java_annotations_inverse
```
  patterns:
    - pattern: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```

However, changing this to "pattern-not" doesn't work, instead it detects everything:
https://semgrep.dev/s/nightwatchcyber:java_annotations_inverse_2
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```

Trying ellipses doesn't help, instead there is an error:
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
          ...
    - pattern-inside: |
        @RequestMapping(...)
        $X $METHOD(...) { ... }
```
Or:
```
  patterns:
    - pattern-not: |
          @RolesAllowed(...)
    - pattern-inside: |
        @RequestMapping(...)
        ...
        $X $METHOD(...) { ... }
```

**Comment by mschwager** [comment] 2021-01-04 15:41
Hi @nightwatchcyber,

We don't have a great, generalized solution for working with arbitrary placement of annotations, but the following works in your specialized case: https://semgrep.dev/s/OPrw/. The problem is there will be a large blow-up of `pattern-not`'s if you have many annotation combinations.

I've often wanted a generalized way for specifying: "find this pattern, in any order." I've tried to describe this more generally (not just annotations) here: https://github.com/returntocorp/semgrep/issues/744.

**Comment by nbrahms** [comment] 2021-01-04 22:59
Hi @nightwatchcyber 

What's the priority of this issue for you? P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

🙇

**Comment by nightwatchcyber** [comment] 2021-01-05 14:13
The solution described above may work for me, I will give it a try.

Regarding priority, this would be a P2.

Thanks again!

**Comment by mschwager** [comment] 2021-01-06 20:14
Closing out, feel free to re-open if this doesn't solve your problem :+1:

**Closed as completed by mschwager** 2021-01-06 20:14 UTC
Labels: user:external, lang:java
