### ISSUE TITLE
Do not wait until the end to flush to the output file

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#2874] opened 2021-04-01 21:45 UTC
**Is your feature request related to a problem? Please describe.**

When running a scan that's taking several hours to complete I wish I had results to work on while it's running. I'm also afraid that if it crashes at some point after 2 or 3 hours I'm going to lose everything semgrep might have found up to now.

**Describe the solution you'd like**

I have a scan running now sitting at 14/22 rules done. I'd love to have the results of those 14 rules that are finished scanning already in the output file.

**Describe alternatives you've considered**

Run semgrep once per rule

**Additional context**

N/A

**Comment by ievans** [comment] 2021-04-02 19:00
thanks @dee-see for making this, I was surprised we didn't have this issue already. Seems like an obvious change and I suspect @aryx / @minusworld have some plans to do this already.

Part of the reason we might be that we expect semgrep to be fast and want it to get faster. Is the corpus you are running on public by chance, or is there anything you can share about it? There is a major perf initiative underway so would love to get some representative samples added to our benchmarking suite. (I think this might have already happened with Gitlab, cc @chmccreery)

**Comment by dee-see** [comment] 2021-04-02 19:25
I was running it on https://github.com/elastic/kibana with the `p/react` ruleset.

**Comment by aryx** [comment] 2021-04-02 19:37
Cc @emjin

**Comment by dee-see** [comment] 2021-07-11 23:28
I would like it but I understand there are more pressing issues :)

**Comment by ievans** [comment] 2021-07-12 00:56
@brendongo @aryx I assume this is much easier now that we've moved functionality into semgrep-core?

**Comment by aryx** [comment] 2021-07-15 09:05
We still capture the stdout of semgrep-core python-side and wait until semgrep-core finishes.
What we can do at least now is you can use --debug and we will print which files are currently processed.
But the findings no.

**Comment by dee-see** [comment] 2021-10-13 13:09
Same as last time :) https://github.com/returntocorp/semgrep/issues/2874#issuecomment-877877952

> I would like it but I understand there are more pressing issues :)

**Comment by ievans** [comment] 2021-10-13 15:20
yes, please keep open. this is at least a bit easier now I think now that more logic has moved into the Ocaml core

**Comment by ievans** [comment] 2021-10-20 16:33
ugh stale bot buggy again

**Comment by aryx** [comment] 2022-01-20 19:50
similar to https://github.com/returntocorp/semgrep/issues/2503#issuecomment-1017750599

**Comment by brendongo** [comment] 2022-02-10 03:39
Closing as duplicate of #2503

**Closed as completed** 2022-04-21 21:38 UTC
Labels: enhancement, priority:low, user:external, planned-project
