### ISSUE TITLE
Fix semgrep-core parsing stats

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3552] opened 2021-07-20 02:40 UTC
We don't know why the new parsing stats on semgrep-core are so much worse than those produced by ocaml-tree-sitter-semgrep.

See for example:
* ocaml-tree-sitter stats: https://dashboard.semgrep.dev/metric/semgrep.tree-sitter.c-sharp.parse.pct
* semgrep-core stats: https://dashboard.semgrep.dev/metric/semgrep.core.c.parse.pct This used to receive ocaml-tree-sitter stats, hence the sharp drop.

The semgrep-core stats include the construction of the semgrep generic AST, unlike the ocaml-tree-sitter stats.

**Comment by aryx** [comment] 2021-08-04 13:10
Dupe of https://github.com/returntocorp/semgrep/issues/3538

**Closed as completed** 2021-08-04 13:11 UTC
Labels: priority:medium, user:internal
