### ISSUE TITLE
Semgrep Gets Into State Returning Zero Results Against Specific Directory

### ISSUE THREAD

**Issue by timfaraci** [semgrep/semgrep#2776] opened 2021-03-17 19:39 UTC
**Describe the bug**
Using Semgrep in `docker run` I got semgrep into a state where if I run against directory named `repositories` it will fail to return results. However running against any other named directory, ie `repositories2` results will be returned. 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
Run the following...
`docker run --user "$(id -u):$(id -g)" --rm -v /mydir:/src returntocorp/semgrep:0.41.1 --config=/src/languages/golang --exclude=/vendor/ --json -o myfile.json --error  --dangerously-allow-arbitrary-code-execution-from-rules repositories    `

**Expected behavior**
Results should be returned.

**Screenshots**
N/A

**What is the priority of the bug to you?**
P1 (important to fix or quite annoying) -- I can work around this with creating random directories, this is not ideal. It however would be very impactful to anyone getting into this state on a server which runs constantly.

**Environment**
Docker semgrep:0.41.1

**Comment by mschwager** [comment] 2021-03-17 20:13
I suspect this has something to do with your local directory layout. Could you provide a minimal directory structure to reproduce?

I'm currently trying with:

```
$ tree repository/
repository/
├── repositories
│   ├── test.py
│   └── test.yaml
└── repositories2
    ├── test.py
    └── test.yaml

2 directories, 4 files
```

Both directories work for me:

```
$ docker run --rm -v /tmp/repository:/src returntocorp/semgrep:0.41.1 --config=/src/repositories/test.yaml --json --error repositories
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
{"results": ...
```

```
$ docker run --rm -v /tmp/repository:/src returntocorp/semgrep:0.41.1 --config=/src/repositories/test.yaml --json --error repositories2
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
{"results": ...
```

And if I try against a non-existent directory I get:

```
$ docker run --rm -v /tmp/repository:/src returntocorp/semgrep:0.41.1 --config=/src/repositories/test.yaml --json --error repositories3
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
{"results": [], "errors": [{"type": "FilesNotFoundError", "code": 2, "message": "File not found: repositories3"}]}
ran 1 rules on 0 files: 0 findings
```

Is there a minimal directory structure you can repro with and provide?

I have a suspicion this could be related to https://github.com/returntocorp/semgrep/issues/1215, but I'm not sure.

**Comment by mschwager** [comment] 2021-03-17 20:23
Unable to reproduce original issue, closing out for now :+1:

**Closed as completed by mschwager** 2021-03-17 20:23 UTC
Labels: bug, feature:docker
