### ISSUE TITLE
Semgrep prints "you forgot to mount the current directory in Docker" even though it's mounted with docker-compose

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#960] opened 2020-06-10 05:50 UTC
_Originally posted by @SarayuR in https://github.com/returntocorp/semgrep/pull/548#issuecomment-641736537_

Could able to run Semgrep successfully in my local. 
Built Semgrep image using the Dockerfile available in develop branch, it errored out while opening it in interactive terminal mode of a Docker container. I did mount the current directory but still got below error : 

you are running semgrep in docker, but you forgot to mount the current directory in Docker: missing: -v "${PWD}:/home/repo/"

Steps to reproduce the error:
1. Built the docker image using Dockerfile available in develop branch.
2. In the Dockerfile added below line :
CMD ["python3", "semgrep.py"]

content in semgrep.py :

import os
import sys

print("hi from inside SemGrep") #testing 
os.system('Semgrep --dangerously-allow-arbitrary-code-execution-from-rules --config rulesfolder myprojectfolder --json')

3. Ran above Docker image using docker-compose.yml and got the following output :

semgrep_1  | hi from inside SemGrep
semgrep_1  | you are running semgrep in docker, but you forgot to mount the current directory in Docker: missing: -v "${PWD}:/home/repo/"
semgrep_sg_1 exited with code 0

_Originally posted by @SarayuR in https://github.com/returntocorp/semgrep/pull/548#issuecomment-641736537_

**Comment by underyx** [comment] 2020-06-10 05:52
@SarayuR could you share the docker-compose.yml file's contents? The mount might be to the wrong directory. We expect to see it at `/home/repo/`, and we print the error message you got if that directory is empty.

**Comment by SarayuR** [comment] 2020-06-10 21:18
Using COPY in Dockerfile to mount the current directory to /home/repo/ worked as opposed to mounting it from docker-compose file. But here are the contents of my docker-compose.yml file :

version: '3'
services:
  semgrep:
    image: semgrep:latest
    ports:
      - 5221:5221
    volumes:
      - ${PWD}:/home/repo
   
Also, can you direct me to OWASP rule coverage to run on Java projects ? The ones available at this link are not reporting much issues : https://github.com/returntocorp/semgrep-rules/tree/develop/java

**Comment by aryx** [comment] 2020-06-12 12:50
yep ran into that too. I had to use /home/repo or unset SEMGREP_IN_DOCKER to make it work.

**Comment by mschwager** [comment] 2020-06-12 15:23
Both building the Docker image locally, and using the existing `returntocorp/semgrep:latest` work for me. Can you try using the Docker Hub version? Here's what I tried:

```
$ docker images | grep semgrep
returntocorp/semgrep latest 44dd0ac46f30 40 hours ago 89.8MB
```

```
$ docker run returntocorp/semgrep:latest --version
0.10.1
```

```
$ cat test.py 
import os.path.join
```

```
$ cat test.yaml 
rules:
- id: import statement
  pattern: import $X
  message: "import statement"
  languages: [python]
  severity: ERROR
```

```
$ cat docker-compose.yml 
version: "3"
services:
  semgrep:
    image: returntocorp/semgrep:latest
    volumes:
      - ${PWD}:/home/repo
```

```
$ docker-compose run semgrep --config test.yaml test.py
test.py
severity:error rule:import statement: import statement
1:import os.path.join
```

Building the Docker image locally using the `Dockerfile` (note, not `Dockerfile.dev`) also works for me:

```
$ docker build -t semgrep:latest .
```

```
$ cat docker-compose.yml 
version: "3"
services:
  semgrep:
    image: semgrep:latest
    volumes:
      - ${PWD}:/home/repo
```

```
$ docker-compose run semgrep --config test.yaml test.py
test.py
severity:error rule:import statement: import statement
1:import os.path.join
```

Can you confirm that neither of these works for you?

**Comment by mschwager** [comment] 2020-06-25 16:55
Closing this out as I was unable to reproduce. Feel free to re-open if you see this again :+1:

**Closed as completed by mschwager** 2020-06-25 16:55 UTC
Labels: bug, user:external, feature:docker
