### ISSUE TITLE
Scan crashes on valid Dockerfile

### ISSUE THREAD

**Issue by redtacos** [semgrep/semgrep#9538] opened 2024-01-04 14:48 UTC
**Describe the bug**
When I scan the following Dockerfile, the semgrep scan crash (engine was killed).

**To Reproduce**
Dockerfile:
```Dockerfile
FROM debian:bookworm-slim

ARG USER_ID=1234
USER $USER_ID:$USER_ID
```
Command:
```
docker run --rm -v "${PWD}:/files" returntocorp/semgrep semgrep scan --config=auto --debug --sarif -o /files/result.sarif /files/Dockerfile
```
Command output:
```
...
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 12 is closed
```
From the output sarif file
```
Error while running rules:
You are seeing this because the engine was killed.
The most common reason this happens is because it used too much memory.
If your repo is large (~10k files or more), you have three options:
1. Increase the amount of memory available to semgrep
2. Reduce the number of jobs semgrep runs with via `-j <jobs>`. We
    recommend using 1 job if you are running out of memory.
3. Scan the repo in parts (contact us for help)
Otherwise, it is likely that semgrep is hitting the limit on only some
files. In this case, you can try to set the limit on the amount of memory
semgrep can use on each file with `--max-memory <memory>`. We recommend
lowering this to a limit 70% of the available memory. For CI runs with
interfile analysis, the default max-memory is 5000MB. Without, the default
is unlimited.
The last thing you can try if none of these work is to raise the stack
limit with `ulimit -s <limit>`.
If you have tried all these steps and still are seeing this error, please
contact us.
   Error: semgrep-core exited with unexpected output
```
**Expected behavior**
- The scan should not crash on a valid Dockerfile.
- When something goes wrong with one file, the whole scan should not crash, instead, an error should be added to the output file.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker

**Use case**
Scan a large repository of Dockerfiles successfully, even if semgrep scan is unhappy with some of the files (valid ones or not)

**Comment by mjambon** [comment] 2024-05-25 00:16
Sorry for the late update. I can't reproduce a problem with this dockerfile and the semgrep command you provided using the current version of semgrep. The dockerfile is well-formed and even if it weren't, it should not cause a crash. I'm closing the issue but let us know if the problem persists.

**Closed as completed by mjambon** 2024-05-25 00:16 UTC
Labels: bug, lang:dockerfile
