### ISSUE TITLE
Semgrep fails to install via pip on python 3.12

### ISSUE THREAD

**Issue by thoward27** [semgrep/semgrep#10613] opened 2024-10-22 20:18 UTC
**Describe the bug**

Pip installation fails using python3.12 on apple M1 mac

**To Reproduce**

Create a new folder, run `uv init`, `uv add semgrep`, then `semgrep`

**Expected behavior**

Semgrep installs correctly

**Screenshots**

```
Traceback (most recent call last):
  File "/Users/thomas/scratch/test-semgrep/.venv/bin/semgrep", line 178, in <module>
    exec_osemgrep()
  File "/Users/thomas/scratch/test-semgrep/.venv/bin/semgrep", line 159, in exec_osemgrep
    os.execvp(str(path), sys.argv)
  File "<frozen os>", line 609, in execvp
  File "<frozen os>", line 632, in _execvpe
OSError: [Errno 8] Exec format error
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Pip install, python3.12.6, apple M1

**Use case**

Continuing to run semgrep

**Comment by kopecs** [comment] 2024-10-23 19:43
Is this potentially the same as https://github.com/semgrep/semgrep/issues/10574?

**Comment by ajbt200128** [comment] 2024-10-29 18:24
Tried on an m1 mac with uv 0.4.26, could not reproduce, assuming it's a duplicate of #10574

**Closed as not planned by ajbt200128** 2024-10-29 18:24 UTC
Labels: bug, priority:high, devops, cli

**Comment by thoward27** [comment] 2024-11-06 22:06
Yeah, this was uv, not semgrep. After upgrading uv semgrep installed correctly. Apologies for not seeing the other issue!
