### ISSUE TITLE
Ability to run `scan --validate` without internet connection

### ISSUE THREAD

**Issue by fopinappb** [semgrep/semgrep#10375] opened 2024-07-11 18:41 UTC
https://github.com/semgrep/semgrep/blob/6fbd7aebf45410a4d3d8167ab63b9d3e8e4c0989/cli/src/semgrep/core_runner.py#L1109

The hardcoded `p/semgrep-rule-lints` prevents me from running `semgrep --validate -f my_ruleset.yml` without the ability to connect to semgrep.dev.

I was looking around the code (mostly pysemgrep one hoping ocaml logic would be the same) but could not find any way to disable this step within validate or specify a custom/local ruleset.

Is there any option that I've missed?

In the ocaml logic I saw something related to `~in_docker` but nothing matching that in the python version.
Or is it possible to call each of the validate steps individually (and not doing the lints ruleset)?

Also, I understood that `--validate` will:
* Parse rule
* Run this lint
* Extra checks from `check_rules`

Only the first is done when we actually use the rule right? Or is `check_rules` as well?
If so, I could just forget about running `--validate`.

**Comment by ievans** [comment] 2024-07-11 22:28
@fopinappb thanks for writing this up -- this is a duplicate of https://github.com/semgrep/semgrep/issues/4620 AFAICT, feel free to continue discussion there!

**Closed as completed by ievans** 2024-07-11 22:28 UTC
Labels: duplicate
