### ISSUE TITLE
Ruby scanning not working in JS version of Semgrep VSCode Extension

### ISSUE THREAD

**Issue by skeymeulen** [semgrep/semgrep#10259] opened 2024-05-17 12:42 UTC
**Describe the bug**
Detection of issues in Ruby files is not working when running the JS version of the extension. This occurs both when running the extension on Mac in JS mode and when using the extension on Windows.

**Extension version:** v1.7.1

**To Reproduce**
Create a file index.rb with the following content
```ruby 
require 'active_record'
require 'models/restaurant'

def show(event:, context:)
  ActiveRecord::Base.establish_connection(
    adapter: 'mysql2',
    host: ENV['RDS_HOST'],
    username: ENV['RDS_USERNAME'],
    password: ENV['RDS_PASSWORD'],
    database: ENV['RDS_DATABASE']
  )

  query = "SELECT * FROM customers INNER JOIN orders ON customers.id = %{id}" % {id: event["id"]}
  # ruleid: activerecord-sqli
  result = Platform.find_by_sql(query)

  # ok: activerecord-sqli
  result2 = Smth.find_by_sql("SELECT * FROM customers INNER JOIN orders ON customers.id = %{id}", {id: event["id"]})
  
  {
    body: [result, resul2]
  }
end
```

When running in non-JS mode, an issue is detected on line 13 (ruby.aws-lambda.security.tainted-sql-string.tainted-sql-string).
When switching to JS mode using the `Semgrep: Use JS` extension setting or when running on Windows, no issues are being detected.

In the Semgrep Output window, I can see an error that I expect is causing the issue
```
found 0 matches, 1 errors

there were 0 skipped targets

Semgrep errors: Failure("Pattern parse error")
```

Testing on different Ruby files with different rulesets, still results in this same error.

**Expected behavior**
Scanning a Ruby file should detect the same issues in JS and non-JS mode

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
VSCode Extension v1.7.1

**Use case**
Scanning Ruby files in VSCode

**Comment by ievans** [comment] 2024-05-17 18:32
cc @ajbt200128

**Comment by ajbt200128** [comment] 2024-05-28 17:21
Duplicate of https://github.com/semgrep/semgrep-vscode/issues/138. Closing this issue

**Closed as completed by ajbt200128** 2024-05-28 17:21 UTC
Labels: bug, feature:editor
