### ISSUE TITLE
Fatal Error: (Failure "null And after remove_not") for pattern-either with pattern-inside and pattern-not-inside

### ISSUE THREAD

**Issue by huonw** [semgrep/semgrep#3914] opened 2021-09-21 04:39 UTC
**Describe the bug**
I'm exploring some rules, and happened across a crash that the CLI tells me to report.

**To Reproduce**

https://semgrep.dev/s/AXjB

Run the following rule on anything, even an empty file 

```yaml
rules:
- id: test
  patterns:
    - pattern-either:
      - patterns:
        - pattern-not-inside: |
            if ...:
              ...
      - pattern-inside: |
          while ...:
            ...
  message: test
  languages:
  - python
  severity: ERROR
```

```
Fatal Error: (Failure "null And after remove_not")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Common.map_filter.(fun) in file "src/pfff/commons/Common.ml", line 988, characters 10-13
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Common.map_filter in file "src/pfff/commons/Common.ml", line 987, characters 2-107
Called from Analyze_rule.remove_not in file "src/optimizing/Analyze_rule.ml", line 119, characters 15-46
Called from Common.map_filter.(fun) in file "src/pfff/commons/Common.ml", line 988, characters 10-13
Called from Stdlib__list.fold_left in file "list.ml", line 121, characters 24-34
Called from Common.map_filter in file "src/pfff/commons/Common.ml", line 987, characters 2-107
Called from Analyze_rule.remove_not in file "src/optimizing/Analyze_rule.ml", line 115, characters 15-46
Called from Analyze_rule.remove_not_final in file "src/optimizing/Analyze_rule.ml", line 133, characters 8-20
Called from Analyze_rule.compute_final_cnf in file "src/optimizing/Analyze_rule.ml", line 432, characters 10-28
Called from Analyze_rule.regexp_prefilter_of_formula in file "src/optimizing/Analyze_rule.ml", line 451, characters 16-35
Called from Common.memoized in file "src/pfff/commons/Common.ml", line 641, characters 14-18
Called from Run_rules.filter_and_partition_rules.(fun) in file "src/engine/Run_rules.ml", line 52, characters 21-60
Called from Stdlib__list.partition.part in file "list.ml", line 283, characters 17-20
Called from Run_rules.filter_and_partition_rules in file "src/engine/Run_rules.ml", line 48, characters 4-585
Called from Run_rules.check in file "src/engine/Run_rules.ml", line 78, characters 4-50
Called from Dune__exe__Main.semgrep_with_rules.(fun) in file "src/cli/Main.ml", line 859, characters 13-122
Called from Dune__exe__Main.iter_files_and_get_matches_and_exn_to_errors.(fun) in file "src/cli/Main.ml", line 644, characters 25-31
Called from Common.set_timeout in file "src/pfff/commons/Common.ml", line 1412, characters 12-16
Re-raised at Common.set_timeout in file "src/pfff/commons/Common.ml", line 1430, characters 6-13
Called from Dune__exe__Main.timeout_function in file "src/cli/Main.ml", line 437, characters 4-87
Called from Stdlib__fun.protect in file "fun.ml", line 33, characters 8-15
Re-raised at Stdlib__fun.protect in file "fun.ml", line 38, characters 6-52
Called from Memory_limit.run_with_memory_limit in file "src/system/Memory_limit.ml", line 59, characters 6-62
Called from Dune__exe__Main.iter_files_and_get_matches_and_exn_to_errors.(fun) in file "src/cli/Main.ml", line 641, characters 17-816
```

**Expected behavior**

Presumably `semgrep` shouldn't crash.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Comment by r2c-demo** [comment] 2021-09-21 04:40
This issue is synced in Linear at https://linear.app/r2c/issue/PA-365/fatal-error-failure-null-and-after-remove-not-for-pattern-either-with.

**Comment by huonw** [comment] 2021-09-21 04:42
Potentially the same as #3802

**Comment by IagoAbal** [comment] 2021-10-04 19:58
I am assuming that you know how to fix your rule @huonw ?

We could perhaps issue a warning and evaluate the `patterns` to the empty set, but I am not sure if that is any better.

This is probably a job for the rule meta-checker (WIP). What makes this a bit special is that a `patterns` does not require at least one positive term _if_ it belongs to a `metavariable-pattern`.

**Comment by huonw** [comment] 2022-01-03 23:31
The issue still reproduces 🤷‍♂️ E.g. at https://semgrep.dev/s/AXjB

```
{"code":2,"level":"error","message":"Semgrep Core ERROR - Fatal error: When running test on __semgrep-internal__benchmark-target__.py: (Failure \"empty And; no positive terms in And\")\n-----[ BEGIN error trace ]-----\nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 854, characters 22-68\nCalled from Stdlib__list.map in file \"list.ml\", line 92, characters 20-23\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 815, characters 15-64\nCalled from Stdlib__list.map in file \"list.ml\", line 92, characters 20-23\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 834, characters 18-65\nCalled from Match_search_rules.matches_of_formula in file \"src/engine/Match_search_rules.ml\", line 946, characters 21-61\nCalled from Match_search_rules.check_rule in file \"src/engine/Match_search_rules.ml\", line 961, characters 4-74\nCalled from Match_search_rules.check.(fun) in file \"src/engine/Match_search_rules.ml\", line 993, characters 15-76\n\n-----[ END error trace ]-----\n","path":"__semgrep-internal__benchmark-target__.py","rule_id":"test","type":"Fatal error"}
{"code":2,"level":"error","message":"Semgrep Core ERROR - Fatal error: When running test on target.py: (Failure \"empty And; no positive terms in And\")\n-----[ BEGIN error trace ]-----\nRaised at Stdlib.failwith in file \"stdlib.ml\", line 29, characters 17-33\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 854, characters 22-68\nCalled from Stdlib__list.map in file \"list.ml\", line 92, characters 20-23\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 815, characters 15-64\nCalled from Stdlib__list.map in file \"list.ml\", line 92, characters 20-23\nCalled from Match_search_rules.evaluate_formula in file \"src/engine/Match_search_rules.ml\", line 834, characters 18-65\nCalled from Match_search_rules.matches_of_formula in file \"src/engine/Match_search_rules.ml\", line 946, characters 21-61\nCalled from Match_search_rules.check_rule in file \"src/engine/Match_search_rules.ml\", line 961, characters 4-74\nCalled from Match_search_rules.check.(fun) in file \"src/engine/Match_search_rules.ml\", line 993, characters 15-76\n\n-----[ END error trace ]-----\n","path":"target.py","rule_id":"test","type":"Fatal error"}
```

De-JSON-ified:

```
Semgrep Core ERROR - Fatal error: When running test on __semgrep-internal__benchmark-target__.py: (Failure "empty And; no positive terms in And")
-----[ BEGIN error trace ]-----
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 854, characters 22-68
Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 815, characters 15-64
Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 834, characters 18-65
Called from Match_search_rules.matches_of_formula in file "src/engine/Match_search_rules.ml", line 946, characters 21-61
Called from Match_search_rules.check_rule in file "src/engine/Match_search_rules.ml", line 961, characters 4-74
Called from Match_search_rules.check.(fun) in file "src/engine/Match_search_rules.ml", line 993, characters 15-76

-----[ END error trace ]-----

Semgrep Core ERROR - Fatal error: When running test on target.py: (Failure "empty And; no positive terms in And")
-----[ BEGIN error trace ]-----
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 854, characters 22-68
Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 815, characters 15-64
Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23
Called from Match_search_rules.evaluate_formula in file "src/engine/Match_search_rules.ml", line 834, characters 18-65
Called from Match_search_rules.matches_of_formula in file "src/engine/Match_search_rules.ml", line 946, characters 21-61
Called from Match_search_rules.check_rule in file "src/engine/Match_search_rules.ml", line 961, characters 4-74
Called from Match_search_rules.check.(fun) in file "src/engine/Match_search_rules.ml", line 993, characters 15-76

-----[ END error trace ]-----
```

**Comment by aryx** [comment] 2022-06-21 13:29
dupe of #5234 which has been fixed.

**Closed as completed by aryx** 2022-06-21 13:29 UTC
Labels: enhancement, priority:low, user:external, good first task, feature:metachecker, error-reporting
