### ISSUE TITLE
[Fix] Fix does not correctly format the code with multiple lines

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4897] opened 2022-03-28 08:44 UTC
**Describe the bug**
When a fix is applied that rewrites code to multiple lines, the indentation of those additional lines is incorrect.

**To Reproduce**
https://semgrep.dev/s/ALj8
https://semgrep.dev/s/pieterdc1:a5w0

**Expected behavior**
Indentation of the code should be correct after applying the fix.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Use case**
Better support for multi line fixes.

**Comment by r2c-demo** [comment] 2022-03-28 08:45
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1043/[fix]-fix-does-not-correctly-format-the-code-with-multiple-lines.

**Comment by emjin** [comment] 2022-03-28 18:18
Looks like duplicate of https://github.com/returntocorp/semgrep/issues/3070

**Comment by emjin** [comment] 2022-03-28 18:18
(Yes...it's been a while 😅)

**Closed as completed by emjin** 2022-03-28 18:18 UTC
Labels: priority:low, feature:autofix
