### ISSUE TITLE
Sgrep seems to be matching on any conditionals with strings

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#391] opened 2020-04-07 00:50 UTC
https://sgrep.live/n9Z

**Comment by ievans** [comment] 2020-04-07 01:04
Regression introduced by https://github.com/returntocorp/sgrep/issues/229

Line #21 in https://sgrep.live/n9Z should not be marked as todo

**Comment by dlukeomalley** [comment] 2020-04-07 01:10
Is this related? I found the behavior confusing.

```py
foo(...)
...
bar(...)
```

Now matches:

```py
foo()
if random() > 0.5:
    for i in range(10):
        bar()
```

**Comment by ievans** [comment] 2020-04-07 03:29
@dlukeomalley that's the intended behavior of the fix to https://github.com/returntocorp/sgrep/issues/229

**Closed as completed** 2020-04-08 12:03 UTC
Labels: bug, user:external, priority:high
