### ISSUE TITLE
Python ParseErrors (whitespace at the last line)

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#1163] opened 2020-06-29 17:26 UTC
**Describe the bug**
In theory, a whitespace only line at the last line would not trigger error.

**To Reproduce**
https://semgrep.live/2Zgr

**Expected behavior**
No error.

**Comment by ievans** [comment] 2020-06-29 17:28
@Isaac0616 thanks for filing this! It looks to me like like it is a duplicate of https://github.com/returntocorp/semgrep/issues/312 -- I'll close this issue to consolidate, but it is still something we'd like to fix.

**Closed as completed by ievans** 2020-06-29 17:28 UTC
Labels: duplicate, lang:python
