### ISSUE TITLE
multiple-cmd-instructions / multiple-entrypoint-instructions  / alias-must-be-unique and duplication warnings when one of the two occurrences are commented out and should have been ignored

### ISSUE THREAD

**Issue by HariSekhon** [semgrep/semgrep#4642] opened 2022-02-09 11:05 UTC
**Describe the bug**
Several false positives such as multiple-cmd-instructions / multiple-entrypoint-instructions  / alias-must-be-unique are being flagged when one of the two lines are commented out and should have been ignored

**To Reproduce**

https://semgrep.dev/orgs/harisekhon/findings?rule=generic.dockerfile.correctness.alias-must-be-unique.alias-must-be-unique%2Cgeneric.dockerfile.correctness.multiple-cmd-instructions.multiple-cmd-instructions%2Cgeneric.dockerfile.correctness.multiple-entrypoint-instructions.multiple-entrypoint-instructions

https://github.com/HariSekhon/Dockerfiles/blob/2791fe753fe913b52170570d7408ecbdfd348c67/awless/Dockerfile#L14

https://github.com/HariSekhon/Dockerfiles/blob/2791fe753fe913b52170570d7408ecbdfd348c67/tcollector/Dockerfile#L43

https://github.com/HariSekhon/Dockerfiles/blob/2791fe753fe913b52170570d7408ecbdfd348c67/serf/Dockerfile#L43

**Expected behavior**
Should ignore the commented lines and not warn about duplicates

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Reduce false positives

**Comment by r2c-demo** [comment] 2022-02-09 11:06
This issue is synced in Linear at https://linear.app/r2c/issue/PA-847/multiple-cmd-instructions-multiple-entrypoint-instructions-alias-must.

**Comment by emjin** [comment] 2022-02-09 18:13
Closing this since we have a Dockerfile parser now! The problem is these rules are still using generic mode and need to be converted to Docker (see the issue linked). We'll get to it when we can, and we also welcome contributions to our rules!

**Closed as completed by emjin** 2022-02-09 18:13 UTC
