### ISSUE TITLE
Go Object Matching

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1719] opened 2020-09-22 21:58 UTC
**Describe the bug**
Go object matching with ellipsis on either side is not matching as expected. 

**To Reproduce**
https://semgrep.dev/s/ere0/

**Expected behavior**
Would expect the pattern to match on the http.Request object.

**Comment by aryx** [comment] 2020-09-23 06:50
I can't load your snippet. I get "Error loading snippet 'ere0': o.replaceAll is not a function"
@chmccreery might know why.

**Comment by chmccreery** [comment] 2020-09-23 15:05
Strange- I think I know what line of code may have caused the error you just mentioned, @aryx, but I am not able to reproduce it (the snippet loads just fine for me?)

**Comment by colleend** [comment] 2020-09-23 16:34
Oh interesting, whenever I try to load the snippet again, I'm also getting the same error @aryx was getting...I'll try to make another semgrep.live link then.

**Comment by chmccreery** [comment] 2020-09-23 17:01
@colleend do you want to screenshare with me and debug together? I think I know the problem roughly, but since I can't reproduce it locally, it would help to be on the call with you.

**Comment by colleend** [comment] 2020-09-23 17:52
Talked to @chmccreery , it was actually the version of JS our web browsers are running that resulted in that error.

**Comment by chmccreery** [comment] 2020-09-23 17:57
We are changing the code so that any web browser can load snippets. Sorry about that, and thanks for filing the issue, @aryx! Fixed in: https://github.com/returntocorp/semgrep-app/pull/685

**Comment by aryx** [comment] 2020-10-06 19:12
@colleend want to take a look at it? Sounds similar to other bugs related to ellipsis you fixed with other languages.
As before you can dump the pattern AST and code AST and figure out in Generic_vs_generic why it does not match.
Note that I've added some logging capability so feel free to ask me if you need to setup logging.

**Comment by colleend** [comment] 2020-10-07 16:31
yes I'll take a look! Yay for logging 🥳

**Closed as completed** 2020-11-12 10:36 UTC
Labels: bug, lang:golang, good first task

**Comment by aryx** [comment] 2020-11-12 11:08
This now works on develop: https://semgrep.dev/s/ere0/?version=develop
