### ISSUE TITLE
Type-awareness for more languages

### ISSUE THREAD

**Issue by Mariia-Kovtun** [semgrep/semgrep#2388] opened 2021-01-13 14:01 UTC
Type-awareness that has appeared for Java and Go (https://r2c.dev/blog/2020/type-awareness-in-semantic-grep/) is a very convinient option, solving some problems.
Is it planned to be added for other languages? (As for me, I'm really waiting for it for Python, JS and C).

**Comment by aryx** [comment] 2021-01-13 17:15
It should be easy to add for C, because the types are in the code; we just need to propagate them from their declaration to their uses. The problem is that for Python and JS, most of the time there is no type; so it has to be inferred, and this is far far more difficult. An option is to rely on LSP servers to get type information, or external tools like typescript or mypy, but again it's a lot of work.

**Comment by mschwager** [comment] 2021-01-14 21:41
Here's an existing issue for C: https://github.com/returntocorp/semgrep/issues/1344

**Comment by aryx** [comment] 2021-01-14 21:52
Note that @emjin was interested in fixing that for c

**Comment by emjin** [comment] 2021-01-21 18:46
This is being added for C! You can follow #1344 for updates there. I've also opened separate issues for Python (#2433) and Javascript (#2434), though, as we noted previously, they're much more difficult!

**Comment by aryx** [comment] 2022-06-01 10:42
Closing this since we added support for typed metavariables for many more languages now (Typescript, C#, Python+mypy, etc.)

**Closed as completed by aryx** 2022-06-01 10:42 UTC
Labels: enhancement, priority:low, pattern:types
