### ISSUE TITLE
Ability to ignore particular rule Id from ruleset while running locally without App 

### ISSUE THREAD

**Issue by raoganeshr** [semgrep/semgrep#5065] opened 2022-04-21 13:33 UTC
**Is your feature request related to a problem? Please describe.**
Currently when I run the ruleset for Docker, pinning the image version is an error. However I would like to continue using Docker ruleset without the pinning rule. Currently I dont have a way to do it

**Describe the solution you'd like**
Ability to pass ignore rule list

**Describe alternatives you've considered**
None

**Use case**
Ability to reuse existing rulesets without having to duplicate the rules and remove the ones I dont want.

**Additional context**

**Comment by r2c-demo** [comment] 2022-04-21 13:35
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1198/ability-to-ignore-particular-rule-id-from-ruleset-while-running. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment] 2022-04-22 17:31
Thanks for reporting this! I'm marking it as a duplicate of #2530

**Closed as completed** 2022-04-22 17:32 UTC
Labels: duplicate, enhancement, priority:medium, user:external, ux
