### ISSUE TITLE
Tab Indented comment on last line of python

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1500] opened 2020-08-12 02:30 UTC
**Describe the bug**
Semgrep fails to parse python file where the last line is a tab indented comment

**To Reproduce**
https://semgrep.dev/gpJ5/

Real life code: https://github.com/dropbox/notouch/blob/master/notouch/util.py#L48

Note that if the comment is indented with spaces the error does not occur and web editor does some indent auto conversion so best to try this locally.

**Comment by aryx** [comment] 2020-08-17 08:34
The problem is that you use 4 spaces for indentation whereas python consider tabs to use 8 spaces,
so if the line before the comment use 8 spaces instead of 4 this will parse.

**Comment by kevincox** [comment] 2020-08-18 13:10
This is definitely a bug. Both the example, and the real world example are accepted by the cpython parser. This is because the parser doesn't care about the indentation of comments. It appears as though semgrep treats the last line of the file as "code" even if it is just a comment. For example adding another line to the example makes it parse correctly.

https://semgrep.dev/OkeL/

Even adding an empty line afterwards is enough https://semgrep.dev/ero8/

**Comment by nbrahms** [comment] 2020-12-03 16:54
@brendongo Do you know which version of semgrep saw this?

I can reproduce on 0.33.

**Comment by nbrahms** [comment] 2020-12-03 16:56
```
➜  cat -t tests/python/comments_indent.py
def test():
    print("hi")
^I# This ends in a tab

➜  semgrep-core -lang python -dump_ast tests/python/comments_indent.py
Pr(
  [DefStmt(
     ({name=EId(("test", ())); attrs=[]; tparams=[];
       info={id_resolved=Ref(None); id_type=Ref(None);
             id_const_literal=Ref(None); };
       },
      FuncDef(
        {fkind=(Function, ()); fparams=[]; frettype=None;
         fbody=Block(
                 [ExprStmt(
                    Call(
                      Id(("print", ()),
                        {id_resolved=Ref(None); id_type=Ref(None);
                         id_const_literal=Ref(None); }),
                      [Arg(L(String(("hi", ()))))]), ())]);
         })))])
```

**Comment by nbrahms** [comment] 2020-12-03 16:57
This appears to have been fixed by other work between issue opening and 0.33.

Please re-open if you can reproduce.

**Closed as completed by nbrahms** 2020-12-03 16:57 UTC
Labels: bug, priority:medium, user:external, lang:python, cannot-reproduce, fixed
