### ISSUE TITLE
[Python] NoTokenLocation exception on matched code

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3007] opened 2021-04-27 13:07 UTC
https://semgrep.dev/s/ok60

**Comment by aryx** [comment] 2021-05-06 08:16
to reproduce:
semgrep-core -e '$ANY' -pvar '$ANY' benchmark-target.py

**Comment by IagoAbal** [comment] 2021-08-04 12:48
These issues were fixed by https://github.com/returntocorp/semgrep/pull/3613. I still get an error with the Playground but I cannot reproduce it locally:
> Could not parse target.py as python

**Comment by emjin** [comment] 2021-09-04 05:23
Appears fixed.

**Closed as completed by emjin** 2021-09-04 05:23 UTC
Labels: priority:low, lang:python, tech debt
