### ISSUE TITLE
typescript parsing bug: support 'export default interface Foo {}'

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2735] opened 2021-03-10 20:25 UTC
See parser failure: https://semgrep.dev/s/Rove

**Comment by aryx** [comment] 2021-03-11 10:00
related: https://github.com/returntocorp/semgrep/issues/1950

**Comment by mjambon** [comment] 2021-03-18 18:21
Marking this as a duplicate of #1995.

**Closed as completed** 2021-03-18 18:21 UTC
Labels: bug, duplicate, user:external, lang:typescript
