### ISSUE TITLE
[Playground] Very general pattern `$XXX` causes parsing error in Python on internal benchmark-target.py file

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2980] opened 2021-04-22 01:02 UTC
**Describe the bug**
Using the pattern `$ANY` would cause parsing error in some Python code.
Changing the pattern to `$ANY(...)` would cease the error.
Not sure what is the exact code causing the issue because the error message seems to always say the error is on line 1.

**To Reproduce**
https://semgrep.dev/s/yzrA/

**Expected behavior**
`$ANY` does not cause parsing error.

**What is the priority of the bug to you?**
P0

**Comment by colleend** [comment] 2021-04-22 21:35
Interesting, using the metavariable $ANY as a pattern doesn't seem to cause an error with any other language. Is there a specific code pattern that you're trying to use `$ANY` to catch?

**Comment by Isaac0616** [comment] 2021-04-22 22:20
It is from the discussion of a workaround: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1617825363120300.

**Comment by aryx** [comment] 2021-04-27 12:57
@underyx feel free to reassign to who can cover your code now.

**Comment by aryx** [comment] 2021-04-27 13:02
The internal bencmark file is here: https://semgrep.dev/s/ok60/
when run locally I get indeed an error:
```Uncaught exception:
  
  Parse_info.NoTokenLocation("Match returned an empty list with no token location information; this may be fixed by adding enclosing token information (e.g. bracket or parend tokens) to the list's enclosing node type.")
```

**Comment by aryx** [comment] 2021-04-27 13:04
I should fix this exception in the CLI, but still there are many wrong things happening here:
 - this is not a parsing error as the playground says, it's a reporting error on a match; we were not able to locate the matched code
 - the error is not even on the target file, it's on an internal file we use in the background; error on such file should not propagate
 -

**Comment by aryx** [comment] 2021-04-27 13:08
tracking the NoTokenLocation exn here: https://github.com/returntocorp/semgrep/issues/3007
but the high priority is not to fix that; it's instead making sure semgrep and the playground and this benchmark code is resilent to such errors (especially when they do not even happen on the target file but on an internal benchmark-target file).

**Comment by underyx** [comment] 2021-04-27 18:14
Identified the cause as this one line: https://github.com/returntocorp/semgrep-app/blob/5fe6046e196eaf0913edf655fab306eebadd684e/server/semgrep_app/controllers/run.py#L149

Will push a fix tomorrow.

**Closed as completed** 2021-04-29 20:20 UTC
Labels: user:external, lang:python, priority:high, feature:matching
