### ISSUE TITLE
ModuleNotFoundError: No module named 'attrs' since 0.83

### ISSUE THREAD

**Issue by vmarkovtsev** [semgrep/semgrep#4794] opened 2022-03-11 11:23 UTC
**Describe the bug**
Executing semgrep raises an exception.

I catch it in the CI: https://github.com/athenianco/athenian-api/runs/5500293758?check_suite_focus=true

It started crashing since 0.83.

```
Traceback (most recent call last):
  File "/home/runner/.local/bin/semgrep", line 5, in <module>
    from semgrep.__main__ import main
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/cli.py", line 6, in <module>
    from semgrep.commands.publish import publish
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/commands/publish.py", line [13](https://github.com/athenianco/athenian-api/runs/5500293758?check_suite_focus=true#step:8:13), in <module>
    from semgrep.config_resolver import get_config
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/config_resolver.py", line 34, in <module>
    from semgrep.error import InvalidRuleSchemaError
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/error.py", line [16](https://github.com/athenianco/athenian-api/runs/5500293758?check_suite_focus=true#step:8:16), in <module>
    from semgrep.rule_lang import Position
  File "/home/runner/.local/lib/python3.8/site-packages/semgrep/rule_lang.py", line [21](https://github.com/athenianco/athenian-api/runs/5500293758?check_suite_focus=true#step:8:21), in <module>
    from attrs import evolve
ModuleNotFoundError: No module named 'attrs'
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment] 2022-03-11 11:26
This issue is synced in Linear at https://linear.app/r2c/issue/PA-958/modulenotfounderror-no-module-named-attrs-since-083.

**Comment by ievans** [comment] 2022-03-11 15:21
Thanks for the report, sorry about the frustration. @brendongo can you take a look? Does it work on Python >=3.9?

**Comment by underyx** [comment] 2022-03-11 15:26
Hi! I'll look at this later today. The issue might be that our version specifier for the attrs library is too relaxed and you have too old of a version. If this is the case, running `pip install --upgrade attrs` should fix the issue for you.

**Comment by ievans** [comment] 2022-03-11 15:32
For reference, from the CI log:

> Requirement already satisfied: attrs>=19.2.0 in /usr/lib/python3/dist-packages (from flake8-bugbear==22.1.11->-r server/requirements-lint.txt (line 2)) (19.3.0)

**Comment by underyx** [comment] 2022-03-11 15:36
Thanks for pasting that in! Semgrep's setup.py requests attrs~=21.0, so I'm not sure why pip wouldn't fetch the correct version :/

Pinning attrs in requirements-lint.txt should fix the issue, I think.

**Comment by vmarkovtsev** [comment] 2022-03-11 17:48
I confirm that pinning attrs to 21.4.0 resolved my problem. Thank you everybody for the help.

**Comment by underyx** [comment] 2022-03-11 18:27
You're welcome @vmarkovtsev, and sorry about the noise! I'll leave this issue open for a little longer to see if we can track down the root cause of why pip wasn't respecting semgrep's new dependency constraints.

**Comment by underyx** [comment] 2022-03-14 22:23
Another user reported that e.g. `21.1.0` is allowed by our version specifier but `21.3.0` is the earliest actually compatible version. We addressed this in https://github.com/returntocorp/semgrep/pull/4808. This might fix your issue as well (although I'm not sure why your CI log would `19.3.0` as the installed attrs version in that case.)

I think that's as far as we will get right now in tracking this issue down so I'll go ahead and close this. We can reopen if needed.

**Closed as completed by underyx** 2022-03-14 22:23 UTC
Labels: bug, devops

**Comment by ben-elttam** [comment] 2022-03-28 21:48
I hit this issue on semgrep 0.86.5, attr 21.4.0, Alpine Linux 3.15.0

# Fixed

There was something wrong with my `attrs` install. Before installing it `import attrs` would fail.
Reinstalling it fixed the issue.

## Before
```
python
Python 3.9.7 (default, Nov 24 2021, 21:15:59)
[GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import attrs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/attrs/__init__.py", line 3, in <module>
    from attr import (
ModuleNotFoundError: No module named 'attr'
```

## After
```
sudo -H pip install --force-reinstall --upgrade attrs
Collecting attrs
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Installing collected packages: attrs
  Attempting uninstall: attrs
    Found existing installation: attrs 21.4.0
    Uninstalling attrs-21.4.0:
      Successfully uninstalled attrs-21.4.0
Successfully installed attrs-21.4.0
```

```
python
Python 3.9.7 (default, Nov 24 2021, 21:15:59)
[GCC 10.3.1 20211027] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import attrs
>>>
```

```
semgrep --version
0.86.5
```

# Problem
## semgrep  `attrs` module error traceback

```
semgrep --version
Traceback (most recent call last):
  File "/usr/bin/semgrep", line 5, in <module>
    from semgrep.__main__ import main
  File "/usr/lib/python3.9/site-packages/semgrep/__main__.py", line 5, in <module>
    from semgrep.cli import cli
  File "/usr/lib/python3.9/site-packages/semgrep/cli.py", line 4, in <module>
    from semgrep.commands.ci import ci
  File "/usr/lib/python3.9/site-packages/semgrep/commands/ci.py", line 16, in <module>
    import semgrep.semgrep_main
  File "/usr/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 17, in <module>
    from semgrep.autofix import apply_fixes
  File "/usr/lib/python3.9/site-packages/semgrep/autofix.py", line 8, in <module>
    from semgrep.error import SemgrepError
  File "/usr/lib/python3.9/site-packages/semgrep/error.py", line 12, in <module>
    import attr  # TODO: update to next-gen API with @define; difficult cause these subclass of Exception
ModuleNotFoundError: No module named 'attr'
```

## Python version

```
Python 3.9.7
```

## semgrep 0.86.5 and attrs 21.4.0

```
 pip list | rg 'semgrep|attrs'
attrs              21.4.0
semgrep            0.86.5
```

## Semgrep up-to-date - with attrs ~= 21.3

```
sudo pip install --upgrade semgrep
Requirement already satisfied: semgrep in /usr/lib/python3.9/site-packages (0.86.5)
Collecting semgrep
  Using cached semgrep-0.86.5-cp37.cp38.cp39.py37.py38.py39-none-any.whl (22.8 MB)
  Using cached semgrep-0.86.3-cp37.cp38.cp39.py37.py38.py39-none-any.whl (22.8 MB)
Requirement already satisfied: click~=8.0 in /usr/lib/python3.9/site-packages (from semgrep) (8.0.3)
Requirement already satisfied: requests~=2.22 in /usr/lib/python3.9/site-packages (from semgrep) (2.26.0)
Requirement already satisfied: defusedxml~=0.7.1 in /usr/lib/python3.9/site-packages (from semgrep) (0.7.1)
Requirement already satisfied: attrs~=21.3 in /usr/lib/python3.9/site-packages (from semgrep) (21.4.0)
Requirement already satisfied: setuptools in /usr/lib/python3.9/site-packages (from semgrep) (52.0.0)
Requirement already satisfied: glom~=22.1 in /usr/lib/python3.9/site-packages (from semgrep) (22.1.0)
Requirement already satisfied: tqdm~=4.46 in /usr/lib/python3.9/site-packages (from semgrep) (4.61.1)
Requirement already satisfied: colorama~=0.4.0 in /usr/lib/python3.9/site-packages (from semgrep) (0.4.4)
Requirement already satisfied: urllib3~=1.26 in /usr/lib/python3.9/site-packages (from semgrep) (1.26.7)
Requirement already satisfied: boltons~=21.0 in /usr/lib/python3.9/site-packages (from semgrep) (21.0.0)
Requirement already satisfied: packaging~=21.0 in /usr/lib/python3.9/site-packages (from semgrep) (21.3)
Requirement already satisfied: click-option-group~=0.5 in /usr/lib/python3.9/site-packages (from semgrep) (0.5.3)
Requirement already satisfied: peewee~=3.14 in /usr/lib/python3.9/site-packages (from semgrep) (3.14.4)
Requirement already satisfied: wcmatch~=8.3 in /usr/lib/python3.9/site-packages (from semgrep) (8.3)
Requirement already satisfied: ruamel.yaml<0.18,>=0.16.0 in /usr/lib/python3.9/site-packages (from semgrep) (0.17.17)
Requirement already satisfied: jsonschema~=3.2 in /usr/lib/python3.9/site-packages (from semgrep) (3.2.0)
Requirement already satisfied: face>=20.1.0 in /usr/lib/python3.9/site-packages (from glom~=22.1->semgrep) (20.1.1)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3.9/site-packages (from jsonschema~=3.2->semgrep) (1.16.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/lib/python3.9/site-packages (from jsonschema~=3.2->semgrep) (0.18.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging~=21.0->semgrep) (2.4.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.9/site-packages (from requests~=2.22->semgrep) (2020.12.5)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/lib/python3.9/site-packages (from requests~=2.22->semgrep) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.9/site-packages (from requests~=2.22->semgrep) (3.3)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in /usr/lib/python3.9/site-packages (from ruamel.yaml<0.18,>=0.16.0->semgrep) (0.2.4)
Requirement already satisfied: bracex>=2.1.1 in /usr/lib/python3.9/site-packages (from wcmatch~=8.3->semgrep) (2.1.1)
```

## All Alpine packages  up-to-date
```
sudo apk update && sudo apk upgrade --available
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.15.2-50-gb346898b86 [http://dl-cdn.alpinelinux.org/alpine/v3.15/main]
v3.15.2-44-gdbb488bd1b [http://dl-cdn.alpinelinux.org/alpine/v3.15/community]
v20220328-19-g02cececb40 [http://dl-cdn.alpinelinux.org/alpine/edge/main]
v20220328-19-g02cececb40 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v20220328-19-g02cececb40 [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 36733 distinct packages available
OK: 2922 MiB in 612 packages
```

**Comment by underyx** [comment] 2022-03-29 00:23
Thanks for the diligent report @ben-elttam!
