### ISSUE TITLE
Tidle (backtick) string in Go not matched

### ISSUE THREAD

**Issue by khanhldt** [semgrep/semgrep#3930] opened 2021-09-24 04:51 UTC
**Describe the bug**
I was investigating replacing GoSec rules with Semgrep, rule G201, and found that it looks like Semgrep is unable to parse backtick Go string, which is unfortunately a quite common way to declare SQL strings in this case.

**To Reproduce**
Rule (for demo purpose only, not the final rule to replace G201):
```yaml
rules:
- id: "gosec.G201"
  patterns:
  - pattern-inside: |
      $Q := fmt.Sprintf("$QUERY", ...)
      ...
  - metavariable-regex:
      metavariable: "$QUERY"
      regex: "select"
  - pattern-either:
    - pattern: "$DB.Query($Q,...)"
  message: SQL query construction using format string
  severity: "WARNING"
  languages: ["go"]
```

Test file that works:
```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf("select region from %s", someVar)
    conn.Query(query)
}
```

Test file that doesn't work:
```
package main

import (
    "database/sql"
    "fmt"
)

func test(conn *sql.DB, someVar string) {
    query := fmt.Sprintf(`select region from %s`, someVar)
    conn.Query(query)
}
```

**Expected behavior**
Expected both test files to have worked with that rule.

**What is the priority of the bug to you?**

- [ x ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Tested using https://semgrep.dev/editor

**Comment by r2c-demo** [comment] 2021-09-24 04:52
This issue is synced in Linear at https://linear.app/r2c/issue/PA-405/tidle-backtick-string-in-go-not-matched.

**Comment by emjin** [comment] 2021-09-24 15:08
This is because Semgrep does not consider backtick strings and quote strings to be equivalent. If you allow both cases, your pattern will work: https://semgrep.dev/s/866N

**Comment by khanhldt** [comment] 2021-09-24 15:53
@emjin Thanks for the solution. I would like to follow up a little bit on this as to whether it's a design decision or can be considered a feature request (if not considered a bug).

Two main things:
- The value proposition of Semgrep is to make writing rules as language agnostic as possible. This backtick string is very Go specific and to some extent just equivalent to `"""` (triple quote) string in some other languages like Python. I haven't tested but do we need to do something similar to the triple quote strings, i.e. `"""$QUERY"""`? I feel like this is something fundamental enough to be supported out of the box.
- I did quite some searching around in the docs and on the web but couldn't find this. If we decide that this is something we don't support, maybe worth adding a note somewhere searchable. For GoLang, this is a bit annoying to have to distinguish the 2 string syntaxes in every rule.

Thanks!

**Comment by emjin** [comment] 2021-09-24 17:29
Thanks for your thoughtful feedback! Indeed `"..."` will match `"""$QUERY"""`. Backtick strings are special because while (to my knowledge) backtick strings in Go are constant strings, in several other languages we support they are not. For example, in Ruby, putting `ls` in backticks will [execute it](https://www.bigbinary.com/blog/backtick-system-exec-in-ruby).

I'm interested in your thoughts on how to balance language agnosticism with ease of use in this case. We could make an exception for Go backtick strings---I see where this is annoying. If not, we should absolutely document this.

**Comment by khanhldt** [comment] 2021-09-24 17:46
@emjin. Thanks for answering. Your example of Ruby case is interesting. 

Just a random thought. Can we have a metadata field that says something along the lines of "please treat backtick string as string"? That can be default to "false", but we document it if we're writing a rule just for "go" language, we may want to switch that on.

Just to illustrate it a bit better:
```
configurations:
 - backtick_string_as_string: true
rules:
- id: ...
```

**Comment by emjin** [comment] 2021-09-24 22:37
That could make sense! Interested in thoughts of @aryx @ievans

**Comment by ievans** [comment] 2021-09-25 00:05
@emjin I'm probably just missing something, but if the we added an equivalence for golang specifically that \`somestr\` is normalized to "somestr" in both pattern and code parsing, that would solve the issue right? Is your concern just with having a one-off equivalence for go specifically? I know we have many one-offs for Python already so I don't think we'd be breaking any design decision.

Solving it that way is my preference. We've also discussed having a more explicit API for builtin types, so that the pattern could look like: `$Q := fmt.Sprintf(($QUERY string), ...)`. I believe some languages have that implemented (Java, Python) but not go apparently, https://semgrep.dev/s/Pbbz errors for me.

The mode switch that @khanhldt suggested is a possibility (and we do have a config section that we could put it in) but is much less discoverable; I think we should avoid those adding config options as much as we can.

**Comment by emjin** [comment] 2021-09-25 02:28
Yes, that would solve this. I’m looking for a second opinion since I’m not familiar with this syntax in Go and don’t know what people might need to look for. This might be overly hesitant; I’m just used to people wanting backtick strings to be differentiated.

**Comment by emjin** [comment] 2021-09-25 06:49
Ok, I checked the Go standard and confirmed that these are always (at least) constant strings. Created https://github.com/returntocorp/semgrep/issues/3938, closing this in favor of that issue

**Closed as completed by emjin** 2021-09-25 06:49 UTC
Labels: user:external, priority:high, feature:matching
