### ISSUE TITLE
Parse Java symbols containing accented characters and the new record extension

### ISSUE THREAD

**Issue by Floby** [semgrep/semgrep#2704] opened 2021-03-05 15:12 UTC
**Describe the bug**
Semgrep fails to parse java code because of diacritics.

**To Reproduce**
Import or declare a symbol containing an accented character.
```java
class Tireur {
  private string cibleVisée;
}
```

**Expected behavior**
semgrep reads the symbol into its AST as javac does.

**What is the priority of the bug to you?**
P0 as our code is standardised to use french words, containing accents where needed.

**Environment**
semgrep@0.41.1 installed via pip on ubuntu 18.04

**Comment by ievans** [comment] 2021-03-05 22:07
Hello @Floby, welcome and thanks for creating an issue with so much detail! 

I believe that there is a bug here but I'm not able to reproduce. I tried on the live editor https://semgrep.dev/s/6n4B and on a local test case with your reproduction having the accent aigu. 

```
ine@imbp4 ~/D/r/t/synthetic> semgrep -e 'class $X { ...  }' --lang=java .
fr.java
1:class Tireur {
2:  private string cibleVisée;
3:}
ran 1 rules on 1 files: 1 findings
```

Can you provide a playground editor (https://semgrep.live) snippet that fails to parse? or more detail about your local setup?

cc @nbrahms or @mjambon who might have more details

**Comment by Floby** [comment] 2021-03-08 09:24
OK, my bad for not testing this code in the sandbox.

this one indicates an error on the accented character (https://semgrep.dev/s/2xeD)

```java

public class Usecase {
    public Usecase() {
    }

    public void exécuter(Commande commande) {
    }

    public static record Commande(String param) {
        public static Commande aPartirDe(Chose chose) {
            return new Commande(chose.enParam());
        }
    }
}
```
However, removing the `record` statement makes semgrep able to parse the file. `record` is still experimental so it makes sense that semgrep does not parse it, but it is still unexpected for the parse error to be reported elsewhere :)

**Comment by aryx** [comment] 2021-03-08 11:05
I think the issue is that we use 2 parsers for Java, the pfff one and tree-sitter one, and both choke on it, but then we report the parse error of pfff.

**Comment by aryx** [comment] 2021-03-08 11:06
We probably now should use first the tree-sitter Java parser instead of pfff one, so the error reported would be the one of tree-sitter.
Also, tree-sitter-java can probably parse partially this file by skipping the record keyword, so @ievans we probably need a way to tell semgrep-app of partial parse errors for the UI to not stop but run the pattern (and possibly highlight a problematic skipped token).

**Comment by Floby** [comment] 2021-03-08 16:51
that would be amazing :) because the second reason preventing us from using semgrep right now is our extensive use of `record`s, even though we probably shouldn't.

**Comment by aryx** [comment] 2021-03-09 09:16
I've created issues upstream in tree-sitter-java.

**Comment by aryx** [comment] 2021-03-11 09:39
To switch to use tree-sitter-java first, they need to fix a few bugs first: https://github.com/tree-sitter/tree-sitter-java/issues/68
After that we will get better error messages for the files containing accents, and correctly point to the 'record' token for the error.

**Comment by DrewDennison** [comment] 2021-04-08 16:54
@Floby thanks for the bug report. We're blocked on tree-sitter supporting unicode. Good news is that @aryx and @mjambon just commit permissions to tree-sitter so it will get fixed eventually but I don't have a definite timeline for you at this time.

**Comment by ievans** [comment] 2021-04-08 17:32
@DrewDennison looks like [unicode is fixed](https://github.com/tree-sitter/tree-sitter-java/issues/60), but record extensions aren't yet?

**Comment by aryx** [comment] 2021-04-08 18:16
@emjin fixed the record extension, but we're waiting for tree-sitter people to merge and fix the CI issues they have with tree-sitter-java.

**Comment by mjambon** [comment] 2021-04-08 23:28
Fixed by https://github.com/tree-sitter/tree-sitter-java/pull/72

**Closed as completed** 2021-04-15 12:49 UTC
Labels: bug, lang:java, priority:high, tree-sitter

**Comment by aryx** [comment] 2021-04-15 14:46
This works now on develop: https://semgrep.dev/s/2xeD?version=develop
Should  be part of the next semgrep release 0.47.0
