### ISSUE TITLE
report error context to sgrep-lint

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#493] opened 2020-04-16 23:34 UTC
**Is your feature request related to a problem? Please describe.**
(First line after command is stderr) Currently parse errors look like this:
```
> sgrep -lang js -e '$X == $X'  ./lib/callback_to_promise.js
airtable.js/lib/callback_to_promise.js:14:33: AST generic error: Weird: literal in call position
{
  "error": "unknown exception",
  "message": "Ast_generic.Error(\"Weird: literal in call position\", _)"
}
```

**Describe the solution you'd like**
If the position information was passed in the JSON output, sgrep-lint could display it as well. This would be helpful for end-users as they don't see the sgrep-core stderr message

**Comment by nbrahms** [comment] 2020-04-17 22:39
@ievens This appears to be a duplicate of #383, so I'll close it. Please reopen if you wish to disambiguate the two.

**Closed as completed by nbrahms** 2020-04-17 22:39 UTC
Labels: duplicate, enhancement
