### ISSUE TITLE
To disable Registry rule metrics, use "--metrics=off".

### ISSUE THREAD

**Issue by Priyadhana** [semgrep/semgrep#4987] opened 2022-04-08 17:52 UTC
I am using semgrep in a jenkins stage. The build fails due to this error. 

![image](https://user-images.githubusercontent.com/48547351/162495097-b4b34b3f-2ca7-46d9-ba12-f3f7db66a45b.png)

I have tried adding --metrics=off and metrics off to semgrep, But it still throws the same error. Not sure what am I missing. 

**Jenkins Stage:**

semgrep_result = sh (script: "semgrep --config=p/ci --metrics off src  --json  --output static-analytics-report.json ",returnStdout: true)

semgrep_result = sh (script: "semgrep --config=p/ci --metrics=off src  --json  --output static-analytics-report.json ",returnStdout: true)

**Comment by r2c-demo** [comment] 2022-04-08 17:53
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1134/to-disable-registry-rule-metrics-use-metrics=off.

**Comment by ievans** [comment] 2022-04-08 17:57
hi @Priyadhana -- can you share a bit more--what is the specific error you are seeing? Metrics on/off should not affect the status code which is what would fail the build. Can you share the rest of the output?

**Comment by Priyadhana** [comment] 2022-04-09 05:31
Hi @ievans , I am getting error code 2. 
![image](https://user-images.githubusercontent.com/48547351/162660180-178f3370-fa73-4422-a71c-004527ceceea.png)

Can you please help me with how should I use metric on/off?

**Comment by brendongo** [comment] 2022-04-11 18:13
Hi. I think you are running a stale version of semgrep. If you upgrade to latest semgrep 0.87.0, `semgrep --config p/owasp-top-ten` should work correctly.

**Comment by ievans** [comment] 2022-04-11 18:38
Yes, dupe of https://github.com/returntocorp/semgrep/issues/4984.

**Closed as completed by ievans** 2022-04-11 18:38 UTC
Labels: need-more-info
