### ISSUE TITLE
Python 'import $X' matches 'from foo import bar'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#806] opened 2020-05-20 20:03 UTC
Consider the following Python file:

```
$ cat test.py 
from foo import bar
```

Both of the following patterns match this statement:

```
$ /tmp/semgrep-files/semgrep --lang python --pattern 'from $X import $Y' test.py
test.py
1:from foo import bar
```

```
$ /tmp/semgrep-files/semgrep --lang python --pattern 'import $X' test.py
test.py
1:from foo import bar
```

It may seem like `import $X` is simply nested within `from $Y import $X`, but in Python these are two different AST types: `ast.Import` and `ast.ImportFrom`, so it's surprising that `import $X` matches `from foo import bar`. This is especially inconvenient when you're considering both cases separately, e.g.

```yaml
pattern-either:
  - pattern: import $X
  - pattern: from $X import $Y
```

The first pattern will supersede the second despite the second pattern more closely matching the equivalent Python statement. I think it would make more sense to Python developers if `import $X` didn't match `from foo import bar`. Even weirder is that `$X` is `foo` in this situation, not `bar`:

```
$ /tmp/semgrep-files/semgrep --json --lang python --pattern 'import $X' test.py | python -mjson.tool
{
    "results": [
        {
            ...
            "extra": {
                "metavars": {
                    "$X": {
                        ...
                        "abstract_content": "foo",
                    }
                },
                ...
                "lines": "from foo import bar"
            }
        }
    ],
    "errors": []
}
```

**Comment by nbrahms** [comment] 2020-05-20 20:21
@mschwager this is actually intended behavior (I think it's even documented that these import scenarios are equivalent).

Removing the bug label here, as this seems more like a documentation issue (or is it an enhancement request?)

**Comment by mschwager** [comment] 2020-05-20 21:18
Per an internal discussion, to recap:

```yaml
pattern-either:
  - pattern: import $X
  - pattern: from $X import $Y
```

Running against `from foo import bar` will give `$X` as `foo` and nothing for `$Y`. This is confusing to me personally. This is intentionally done for ease of implementation on the backend, but there's some discussion to be had about ease of implementation vs. UX.

**Comment by ievans** [comment] 2020-06-05 16:50
Closing this @mschwager per discussion as it's intended behavior for now.

**Closed as completed by ievans** 2020-06-05 16:50 UTC
Labels: lang:python
