### ISSUE TITLE
Investigate failure report from M1 / ARM64

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#2466] opened 2021-01-27 03:14 UTC
**Is your feature request related to a problem? Please describe.**
Make sure semgrep works in ARM docker containers. @ajinabraham noticed Semgrep failed to run on a M1 Mac

**Comment by brendongo** [comment] 2021-01-27 04:51
Duplicate of https://github.com/returntocorp/semgrep/issues/2432 ?

**Comment by underyx** [comment] 2021-01-28 17:56
@DrewDennison @ajinabraham can we get a more detailed report of how it failed? Did x86 emulation not work correctly?

**Comment by aryx** [comment] 2021-04-13 10:32
possible related issue discussed on slack: https://r2c-community.slack.com/archives/CK86BJ5DW/p1617739952157800

**Comment by aryx** [comment] 2021-04-13 10:34
closing, duplicate of #2432

**Closed as completed by aryx** 2021-04-13 10:34 UTC
Labels: user:external, need-more-info
