### ISSUE TITLE
Statically detect unused metavariable-regex (or metavariable-regexp with wrong scope)

### ISSUE THREAD

**Issue by JoelPagliuca** [semgrep/semgrep#2664] opened 2021-03-01 02:51 UTC
**Describe the bug**
in simple cases this isn't obviously obstructive, but in cases with lots of `pattern-either`s we found this forced us to split our rules across multiple files with lots of duplicated logic

**To Reproduce**
https://semgrep.dev/s/4xK5 produces no results
https://semgrep.dev/s/PJKz produces 1 result

**Expected behavior**
1 result for both examples

**What is the priority of the bug to you?**
P1 - quite annoying

**Environment**
`brew` distributed `v0.41.1`

**Comment by ievans** [comment] 2021-03-01 22:36
thanks for the clear reproductions, I agree this looks like a bug! Probably need an optimization to not filter if metavariable didn't occur in patterns, @aryx a case for a new feature easy to enable in the core now?

**Comment by mschwager** [comment] 2021-03-02 17:44
The `metavariable-regex` functionality will notify of this if you run with `--debug` locally:

```
$ echo 'set("hello maintainers")' | python -m semgrep --debug --config /tmp/metavariable.yaml -
loaded 1 configs in 0.04578685760498047
running 1 rules from 1 config /tmp/metavariable.yaml_0 
running 1 rules...
Running rule tmp.my_pattern_id...


--> rule (tmp.my_pattern_id) has findings on filepath: /tmp/tmpeacuze2n
after filter 'and': {<Range start=0 end=24 vars={'$SET': '4e1fedb0242220863f38d97b0e28db56'}>}
after filter 'metavariable_regex': {<Range start=0 end=24 vars={'$SET': '4e1fedb0242220863f38d97b0e28db56'}>}
metavariable '$UNUSED' missing in range '<Range start=0 end=24 vars={'$SET': '4e1fedb0242220863f38d97b0e28db56'}>'
after filter 'metavariable_regex': set()
after filter 'and_all': set()
compiled result set()
--------------------------------------------------------------------------------
...ran on 1 files
semgrep ran in 0:00:00.256416 on 1 files
findings summary: 0 warning
ran 1 rules on 1 files: 0 findings
```

We could always promote this to a warning so we wouldn't need `--debug`:

```
$ echo 'set("hello maintainers")' | python -m semgrep --config /tmp/metavariable.yaml -
running 1 rules...
metavariable '$UNUSED' missing in range '<Range start=0 end=24 vars={'$SET': '4e1fedb0242220863f38d97b0e28db56'}>'
ran 1 rules on 1 files: 0 findings
```

This doesn't totally solve the Semgrep App editor issue, but it's a start.

> Probably need an optimization to not filter if metavariable didn't occur in patterns ...

It's not clear to me that this is strictly _better_, at least until we have metavariable propagation (https://github.com/returntocorp/semgrep/issues/2548). It seems like this approach would trade "false" negatives (is it false if it's a operation that cannot be fulfilled?), for false positives. **Although false positives could be considered superior because they at least tell you something.**

Until we have metavariable propagation, "unused" is somewhat of a loaded term. Many metavariables will be considered unused across patterns. Although, maybe this is another good reason to **not** filter in this case. E.g.

```yaml
rules:
- id: my_pattern_id
  patterns:
  - pattern-inside: |
        def $FUNC(...):
            ...
  - pattern: return ...
  - metavariable-regex:
      metavariable: '$FUNC'
      regex: '(foo|bar)'
  message: |
    Semgrep found a match
  severity: WARNING
  languages: [python]
```

```python
def foo():
    return 1

def bar():
    return 2

def baz():
    return 3
```

```
$ python -m semgrep --config /tmp/metavariable.yaml /tmp/metavariable.py 
running 1 rules...
metavariable '$FUNC' missing in range '<Range start=40 end=48 vars={}>'
metavariable '$FUNC' missing in range '<Range start=65 end=73 vars={}>'
metavariable '$FUNC' missing in range '<Range start=15 end=23 vars={}>'
ran 1 rules on 1 files: 0 findings
```

Thoughts?

**Comment by mschwager** [comment] 2021-03-22 13:51
Any thoughts here? Would a warning on the CLI be sufficient, or are you looking for improvements to the cloud editor?

**Comment by aryx** [comment] 2021-03-22 14:23
I'm working with @emjin on a metachecker for our rules; this would be a good check, that is a metavariable-regexp should be part of a conjonction where the metavariable is mentioned in one of the AND pattern.

**Comment by aryx** [comment] 2021-03-22 14:24
And if one of the AND is an either, then all the either should define the metavariable.

**Comment by aryx** [comment] 2021-03-22 14:31
and in your example @mschwager  the metachecker will not issue a warning, because one of the pattern in the AND define the metavariable (we could force the user to group the pattern-inside and metavariable-regexp in a nested patterns:, but we could do the transformation ourselvers internally).

To answer @ievans " Probably need an optimization to not filter if metavariable didn't occur in patterns," we should not accept the rule instead. The rule has an error in it; all metavariables in metavariables-regexp must be used, otherwise it's like ANDing with an empty set.

**Comment by aryx** [comment] 2021-03-22 14:39
And in your example @mschwager semgrep currently returns 2 matches actually (as it should).

**Comment by aryx** [comment] 2021-03-22 14:41
I'd probably write the rule like this though:
```
rules:
- id: my_pattern_id
  patterns:
  - patterns:
    - pattern-inside: |
        def $FUNC(...):
            ...
    - metavariable-regex:
        metavariable: '$FUNC'
        regex: '(foo|bar)'
  - pattern: return ...
  message: |
    Semgrep found a match
  severity: WARNING
  languages: [python]
```

**Comment by mschwager** [comment] 2021-03-24 14:28
Since the focus has moved to statically detecting this kind of thing I'm going to unassign myself :+1:

**Comment by aryx** [comment] 2021-03-24 15:38
You're more than welcome @mschwager to contribute to this new metachecker if you want.

**Comment by nbrahms** [comment] 2021-04-05 15:33
@ievans @JoelPagliuca I think for the sake of getting this proper prioritization, I'm going to remove the `bug` label (@ievans unless you see a specific thing in the program that can be fixed to resolve this).

cc. @DrewDennison for feature prioritization.

**Comment by aryx** [comment] 2021-07-04 17:32
👋

**Comment by IagoAbal** [comment] 2021-10-04 12:44
I think in the meantime we could still issue a runtime warning when we encounter this kind of thing, we already do this for `metavariable-pattern`.

**Comment by aryx** [comment] 2022-01-04 15:57
:wave:

**Comment by aryx** [comment] 2022-03-09 11:28
@emjin can we close this? Does it work now?

**Comment by emjin** [comment] 2022-03-09 18:19
It works with `--validate` but I think this issue was asking for a warning to surface in the semgrep run. I don't know if I think that makes sense? Maybe adding `--validate` to the editor would be a better way to solve this issue? If that makes sense, we can close this issue in favor of something like "use --validate in more places"

**Comment by aryx** [comment] 2022-03-09 19:34
We should definitely use the metachecker in the playground.

**Closed as completed** 2022-03-09 19:35 UTC
Labels: priority:medium, user:external, feature:metachecker, feature:metavariable-regex
