### ISSUE TITLE
Metavariable-regex is anchored

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4807] opened 2022-03-14 22:14 UTC
Per docs, this should be unanchored:

https://semgrep.dev/s/KgRY

**Comment by r2c-demo** [comment] 2022-03-14 22:16
This issue is synced in Linear at https://linear.app/r2c/issue/PA-980/metavariable-regex-is-left-anchored.

**Comment by aryx** [comment] 2022-06-01 10:24
@mjambon can we close this issue?

**Comment by mjambon** [comment] 2022-06-02 07:52
@aryx no, I didn't touch that. I wasn't aware of this bug. For example, the pattern `a` should match `xxa` but currently, it doesn't. The issue is apparently that the regexp is matched at the beginning of the string using something like `Pcre.pmatch` instead of being matched successively at all the positions in the string using the appropriate function.

**Closed as completed** 2022-06-08 08:02 UTC
Labels: bug, user:external
