### ISSUE TITLE
Can't find dangerouslySetInnerHTML in React (javascript)

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1791] opened 2020-10-07 09:30 UTC
Can't find dangerouslySetInnerHTML={this.rawMarkup()}
https://semgrep.dev/s/P9xE/

**Comment by mschwager** [comment] 2020-10-07 15:50
Hi @dvyakimov,

Thanks for finding this. This appears to be a problem with our JSX parsing. For example, the following pattern works: https://semgrep.dev/s/0gqJ/. However, if we use the ellipsis operator inside the tag it doesn't work: https://semgrep.dev/s/q638/.

@aryx do we expect `...` to work inside JSX tags?

**Comment by aryx** [comment] 2020-10-08 12:54
The issue is that what is inside the body of a JSX element is interpreted as text by Javascript.
You can do <div>THIS IS WHATEVER TEXT YOU WANT</div>
and so if your text looks like code, semgrep does not know about it, so you need to use string-related pattern features to match it,
for example the =~/regexp/ feature in semgrep (but I'm not sure they currently work for the XHP BODY).

**Comment by aryx** [comment] 2020-10-08 12:55
if dangerouslySetInnerHTML was a JSX attribute, as in <div attr1=value attr2=value dangerouslySetInnerHTML=value>TEXT</div>
then things would be different, because semgrep understand that attributes are not just any text.

**Comment by DrewDennison** [comment] 2020-10-15 16:58
@dvyakimov I think the react code is not valid (dangerous react) did you mean something like https://semgrep.dev/s/Ok6b ?

**Comment by DrewDennison** [comment] 2020-10-19 18:06
@dvyakimov did you get a chance to look at the above?

**Comment by DrewDennison** [comment] 2020-10-20 16:50
Closing this for now but feel free to reopen if you still see this issue.

**Closed as completed by DrewDennison** 2020-10-20 16:50 UTC
Labels: bug, lang:javascript
