### ISSUE TITLE
Error with --json flag

### ISSUE THREAD

**Issue by rttwge** [semgrep/semgrep#1210] opened 2020-07-08 02:02 UTC
I'm receiving the following error from the github workflow (shown at the end of message and I added line-feeds for readability). I previously issued a bug for --sarif because the output didn't match the schema specified so I switched to json output for now. Here is what I run from the command line:

semgrep --config=r2c --strict --json ./sourcecode

With --sarif, other than following the spec for output format, what was produced looked good. With --json it doesn't appear I'm getting very far.

Note: Same error occurs using Python 3.8.3

Thanks,

Rick

```Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.11/x64/bin/semgrep", line 8, in <module>
    sys.exit(main())

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/__main__.py", line 11, in main
    cli()

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/cli.py", line 340, in cli
    no_git_ignore=args.no_git_ignore,

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/output.py", line 192, in managed_output
    output_handler.close()

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/output.py", line 301, in close
    output = self.build_output(self.settings.output_destination is None,)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/output.py", line 351, in build_output
    debug_steps,

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/site-packages/semgrep/output.py", line 145, in build_output_json
    return json.dumps(output_json)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)

  File "/opt/hostedtoolcache/Python/3.6.11/x64/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)

TypeError: Object of type 'CoreException' is not JSON serializable
##[error]Process completed with exit code 1.```

**Comment by brendongo** [comment] 2020-07-08 03:22
@rttwge it looks like one of our internal exceptions was not being handled correctly. We added some more strict typing to our exception handling in our next release which should come out later today that should fix this issue.

**Comment by ievans** [comment] 2020-07-08 16:55
@rttwge semgrep 0.14 was released a few hours ago--could you try this issue on that version? (or if you provide a reproducing test case, we can try it).

**Comment by rttwge** [comment] 2020-07-09 03:23
Hello Isaac,

This arrears to have fixed the problem. There was an error in the file
jquery.dataTables.min.js and in the json output was the information below.
The rest of the json file contained results showing concerns as expected.

Thanks,

Rick


errors section of json output.

...
"errors": [
    {
      "type": "SourceParseError",
      "code": 3,
      "short_msg": "parse error",
      "long_msg": "Could not parse jquery.dataTables.min.js as javascript",
      "level": "warn",
      "spans": [
        {
          "start": {
            "line": 1,
            "col": 1
          },
          "end": {
            "line": 1,
            "col": 1
          },
          "source_hash":
"32c80b0e279871a7866402b071539a978ce84800330d2fe275d0e51da24a26ba",
          "file": "jquery.dataTables.min.js",
          "context_start": null,
          "context_end": null
        }
      ],
      "help": "If the code appears to be valid, this may be a semgrep bug."
    }

**Comment by ievans** [comment] 2020-07-10 06:42
@rttwge thanks! I'm going to close this issue as it's fixed in the latest release. I found a version of jquery.dataTables.min.js online that matched that hash and created #1231 to track the parse bug. 

Can you comment on that issue with a sense of prioritization? Generally we don't find people that interested in running over minified files, so just curious if this is a blocker for you.

**Closed as completed by ievans** 2020-07-10 06:42 UTC
Labels: bug, user:external, feature:cli-output

**Comment by ghost** [comment] 2020-08-21 11:04
Looks like version .20 introduced the same error. .19 was working.

Thanks,

Rick

**Comment by ievans** [comment] 2020-08-21 15:15
@rttinfosec could you provide a reproduction example and open a new issue? 

I looked at #1231 again and ran it with the latest docker image (https://semgrep.dev/YG5W?version=develop) but it runs ok
