### ISSUE TITLE
Add flag on CLI for filtering rules

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4746] opened 2022-03-03 17:07 UTC
**Is your feature request related to a problem? Please describe.**
With `--config auto` now live, there will be times (like [this one](https://r2c-community.slack.com/archives/C018NJRRCJ0/p1646326507721369)) where someone gets rules they don't want.

**Describe the solution you'd like**
A CLI flag which permits filtering of rules would be nice for quickly getting the results you want.

**Describe alternatives you've considered**
Alternatively, we could link auto-generated rulesets to the app and have people manage it there.

**Use case**
A quick evaluation of the rules automatically recommended by `--config auto`

**Additional context**
- [x] P1: Regular thing that would be nice to have fixed

**Comment by r2c-demo** [comment] 2022-03-03 17:08
This issue is synced in Linear at https://linear.app/r2c/issue/PA-923/add-flag-on-cli-for-filtering-rules.

**Comment by LewisArdern** [comment] 2022-03-03 17:12
Large organizations have a lot of different pipelines where they may want to remove rules via the CLI especially in less than ideal set-ups.

- Different teams have various levels of expectations, some may want to remove rules from a registry definition 
- Some do not have the luxury of pulling from disk and may just need to use a registry rule, having this feature will save time than having to create a new 'registry' package or writing -f -f -f -f -f 50 times to use all the rules you need

**Comment by ievans** [comment] 2022-03-03 17:25
See also https://github.com/returntocorp/semgrep/issues/2530

**Comment by emjin** [comment] 2022-03-07 19:33
Would appreciate some validation on whether adding this flag would be good for our interface. @brendongo @underyx

**Comment by underyx** [comment] 2022-03-07 19:58
I'm supportive of this. I'd also like if we could merge the `--severity` flag into the same rule-filtering flag as this.

**Comment by xmo-odoo** [comment] 2022-03-10 09:35
> I'm supportive of this. I'd also like if we could merge the `--severity` flag into the same rule-filtering flag as this.

Maybe a rules-filtering DSL similar to e.g. [mercurial's revsets](https://www.mercurial-scm.org/repo/hg/help/revsets)? Which would allow selecting rules along multiple axis with the ability to combine them via boolean / set operators?

Obvious selection attributes would be id, severity, and language. But possibly rules could grow additional fields with the sole purpose of selection e.g. "tags" or "categories" (which would be a bit like `languages` but without any technical meaning for semgrep, and organisations could use that for arbitrary classification and filtering)

**Comment by xmo-odoo** [comment] 2022-03-25 06:44
> This issue is being marked `stale` because there hasn't been any activity in 14 days and either it wasn't prioritized or its priority is high. Please apply the appropriate `priority:*` label before removing the `stale` label.

![agree 2](https://user-images.githubusercontent.com/7571158/160068638-f0074589-83b9-46f9-b49a-ea9e379b1adb.png)

**Comment by aryx** [comment] 2022-06-21 14:20
dupe of #2530

**Closed as completed by aryx** 2022-06-21 14:20 UTC
Labels: priority:low, feature:cli-output, feature:cli-ux, jsonnet
