### ISSUE TITLE
javascript ... overly greedy

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#856] opened 2020-05-28 18:40 UTC
For the pattern:

```
Object.defineProperty(..., {
  get: function (){
    ...
     return ...;
   }
});
```
doesn't match:

```

Object.defineProperty(p, "age", {
    get: function (){
        // no returns.
        return "foo"
    }
});
```

However, removing the ... on line #3 of the pattern does work. See broken example at https://semgrep.live/OrlB

**Comment by nbrahms** [comment] 2020-06-04 23:28
Hi @ievans . Thanks for the bug report. FYI this appears to be a duplicate of #443 . I'm going to close it as such. Please respond and reopen with a comment if I misunderstand this ticket.

**Closed as completed by nbrahms** 2020-06-04 23:28 UTC
Labels: bug, duplicate, pattern:ellipsis
