### ISSUE TITLE
Semgrep sometimes takes 6 hours and sometimes 3 mins on the same files

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#3413] opened 2021-06-24 15:36 UTC
**Describe the bug**
The nightly integration tests sometimes take 6 hours

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by DrewDennison** [comment] 2021-06-24 15:37
@nbrahms can you please dig up the links to the slow CI jobs when you have a minute?

**Comment by IagoAbal** [comment] 2021-08-26 15:02
I believe this, at the end, might have been Git/network related? cc @emjin @mjambon

**Comment by emjin** [comment] 2021-08-26 17:16
Before we ran the integration tests with `--debug`, we would see this both in git commands and in semgrep calls. After adding `--debug`, we only saw this in the git commands (`git checkout` would take forever).

**Comment by mjambon** [comment] 2021-08-26 22:29
I don't know about the causes, but given the difficulty to reproduce these issues, I'd say we should program defensively. Perhaps we should ensure than any command involving "the network" (or any resource out of our control) times out reasonably and with a good error message.

I just created this task for implementing timeouts everywhere: https://github.com/returntocorp/semgrep/issues/3769

**Comment by DrewDennison** [comment] 2021-08-26 22:37
awesome! Love the idea of being more defensive in our programming here

**Comment by emjin** [comment] 2021-12-06 20:03
What is the current state of this? We fixed a couple things related to this

**Comment by IagoAbal** [comment] 2021-12-07 10:08
I think we can close this once @mjambon created #3769.

**Closed as completed** 2021-12-10 01:46 UTC
Labels: performance, devinfra
