### ISSUE TITLE
Add support for metavariable equality statement in Golang

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1318] opened 2020-07-21 20:01 UTC
Pulling from #1316.

Test: `semgrep-core/tests/go/metavar_equality_stmt.go`

```
package main

import "fmt"

func main() {
	//ERROR:
	if x > 2 {
		fmt.Println("hello world")
		fmt.Println("goodbye world")
	} else {
		fmt.Println("hello world")
		fmt.Println("goodbye world")
	}

	if x > 2 {
		fmt.Println("hello world")
		fmt.Println("goodbye world")
	} else {
		fmt.Println("hello world")
	}
}
```

**Comment by ievans** [comment] 2020-07-23 07:18
Duplicate of https://github.com/returntocorp/semgrep/issues/1292

**Closed as completed** 2020-07-23 07:19 UTC
Labels: enhancement, lang:golang
