### ISSUE TITLE
C# parser bug: ellipsis operator doesn't work for method args

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#3415] opened 2021-06-24 18:48 UTC
Doesn't work: https://semgrep.dev/s/grYo
Works: https://semgrep.dev/s/34rg

from @chgg-kboberg

**Comment by Sjord** [comment] 2021-06-25 13:51
This looks like a duplicate of #3289.

**Comment by aryx** [comment] 2021-06-28 09:11
closing, duplicate.

**Closed as completed by aryx** 2021-06-28 09:11 UTC
Labels: bug, lang:c#, alpha
