### ISSUE TITLE
Missing "suppressions" in SARIF output for semgrep ci

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#5007] opened 2022-04-12 17:07 UTC
**Describe the bug**
I used to run scans with semgrep-agent in diff mode, with the SARIF output, and it supported "suppressions" in the SARIF output.
It seems that the `semgrep ci` new method is not reporting to me the issues, I see in the scan logs that it finds all issues, then only reports a part of it, and it's not mentioned in the SARIF file.
I also checked the `--enable-nosem` and it's enabled by default according to the cli doc, so I guess this means "no sem enabled, will report them" ? but still nothing in the SARIF output

**To Reproduce**
I guess it's simple enough to create a file to be scanned and add a comment with // nosemgrep, the tricky part might be scanning on 2 branches though, not sure if this is the bug root cause.
```
semgrep 0.87.0 on python 3.10.4
Scanning across multiple languages:
    <multilang> | 44 rules × 2 files
           java | 53 rules × 1 file 

  Current version has 4 findings.

Switching repository to baseline commit '20f88xxxxxx'.

....

Scanning 1 file.
Returning to original head revision 63686xxxxxx

Some files were skipped.
  Scan was limited to files changed since baseline commit.
....
 Ran 295 rules on 1 file: 2 findings.
Ran 295 blocking rules, 0 audit rules, and 0 internal rules used for rule recommendations.
```
**Expected behavior**
The SARIF output of a diff-aware scan should still produce suppressed findings inside

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
I'm running semgrep in a github action, without the api token, reporting directly SARIF in a PR comment

**Use case**
What will fixing this bug enable for you?
Just improve the scan details provided in the comment

**Comment by r2c-demo** [comment] 2022-04-12 17:07
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1154/missing-suppressions-in-sarif-output-for-semgrep-ci.

**Comment by meriouma** [comment] 2022-04-14 02:12
Not sure if it's related. But we were using 0.80.0 with sarif output, and in one file we had a `// nosemgrep` that worked :
```
window.APP_CONFIG = {{ appConfig }}; // nosemgrep: generic.html-templates.security.var-in-script-tag.var-in-script-tag
```
In 0.87.0 and 0.88.0, the issue is being included in the report as a finding. Tested back to 0.84, and it seems that the problem appears in 0.85.0

**Comment by brendongo** [comment] 2022-05-02 23:24
This should be fixed by https://github.com/returntocorp/semgrep/pull/5116 and should go in on 0.91.0

**Comment by ajbt200128** [comment] 2022-05-24 20:57
> Not sure if it's related. But we were using 0.80.0 with sarif output, and in one file we had a `// nosemgrep` that worked :
> 
> ```
> window.APP_CONFIG = {{ appConfig }}; // nosemgrep: generic.html-templates.security.var-in-script-tag.var-in-script-tag
> ```
> 
> In 0.87.0 and 0.88.0, the issue is being included in the report as a finding. Tested back to 0.84, and it seems that the problem appears in 0.85.0

That's expected behavior, if you have `// nosemgrep` it should still appear in the sarif output and reports, with
```json
"suppressions": [{
       "kind": "inSource"
}]
```
included in change artifact :). This issue is regarding the fact that with diff aware mode, there is no change artifact or mention at all of lines that have `// nosemgrep` in the sarif output

**Closed as completed** 2022-05-27 16:44 UTC
Labels: bug, priority:medium
