### ISSUE TITLE
Fails to parse when last line is comment

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#603] opened 2020-04-28 23:10 UTC
semgrep fails to parse (throws LexicalError) when the last line of a file is a comment

```
foo = 1
# this is a comment
```

https://semgrep.live/NXx

**Comment by ievans** [comment] 2020-04-28 23:11
duplicate of https://github.com/returntocorp/semgrep/issues/240

**Closed as completed by ievans** 2020-04-28 23:11 UTC
Labels: bug
