### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#2252] opened 2020-12-14 18:48 UTC
Prioriry: Low

**Is your feature request related to a problem? Please describe.**
Was trying to use semgrep on my android tablet. 
install is successful, but cannot invoke semgrep.

```
File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/semgrep/util.py", line 135, in sub_run
    result = subprocess.run(cmd, **kwargs)  # nosem: python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.9/subprocess.py", line 1817, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'semgrep-core'
- Semantic Grep  13
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/njsscan", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/njsscan/__main__.py", line 66, in main
    scan_results = NJSScan(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/njsscan/njsscan.py", line 37, in scan
    result = scanner.scan()
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/libsast/scanner.py", line 64, in scan
    results['semantic_grep'] = SemanticGrep(
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 37, in scan
    self.format_output(sgrep_out)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 42, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
```
I guess this is because the binary was not targeted for ARM.

**Describe the solution you'd like**

Would be nice to have a arm compatible semgrep-core

**Describe alternatives you've considered**

**Additional context**
Not top priority.

**Comment by mschwager** [comment] 2020-12-15 18:49
Hi @ajinabraham,

We currently only target x86 Linux and macOS in our `semgrep-core` build. Including ARM builds is low priority for now. I'll leave this open so others with this request can chime in :+1:

**Comment by aviam** [comment] 2021-12-05 08:42
We need it on ARM64 architecture, is it possible to support it?

**Comment by raianul** [comment] 2022-03-31 21:23
Hello Can we have a update on this?

**Comment by brendongo** [comment] 2022-04-01 19:03
We have ARM release supported current penciled in for mid May potentially

**Comment by NEllusion** [comment] 2022-04-12 16:42
This would be awesome for our development teams 👍

**Comment by aryx** [comment] 2022-06-01 10:39
@brendongo Would this be solved by the recent PR #5373 ?

**Comment by ajbt200128** [comment] 2022-06-02 21:29
> @brendongo Would this be solved by the recent PR #5373 ?

No, this PR only adds mac m1 support, not linux/arm64

**Comment by aryx** [comment] 2022-06-21 09:57
I think most people who asked for ARM support really just wanted it for Mac M1, so closing.
If anyone disagree, feel free to reopen and we can make it explicit that we want
Linux/ARM support or something else.

**Comment by miles-slalom** [comment] 2022-06-30 21:00
My team ran into this today -- semgrep failing to run on an ARM64 Linux build agent.

**Comment by caglarsayin** [comment] 2022-10-27 13:54
There is no pip wheel for ARM64 Linux machines. Can you please add it to pypi?

**Comment by VaismanLior** [comment] 2022-11-14 14:23
Tried to install semgrep with pip in a docker container running on my M1 and got this message.
![Screen Shot 2022-11-14 at 16 03 56](https://user-images.githubusercontent.com/97836016/201683924-f5939b4c-2320-41d5-915d-61a3c4f7196f.png)

Is it planned to add support?

**Comment by ldtjcdrs** [comment] 2022-12-01 20:29
FWIW, building from source on Linux aarch64 works after monkey-patching https://github.com/returntocorp/semgrep/blob/9184c109b418b36adeeae9f8e5f28b9228fd9769/cli/src/semgrep/cli.py#L50

**Comment by disposedtrolley** [comment] 2022-12-08 05:59
I noticed that `abort_if_linux_arm64()` was [introduced recently](https://github.com/returntocorp/semgrep/pull/6313). Prior to this I was able to run Semgrep within a Docker container on my M1 Mac, without resorting to the [--platform flag](https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images) to run it under x86 emulation.

It seemed to run without any obvious issues and was quite performant. After this change I've had to run the container with `--platform linux/amd64` which incurs a significant performance hit.

I couldn't find anything in the PR about why this change was made.

**Comment by aryx** [comment] 2022-12-08 10:04
@brendongo @spencerdrak do you know why we added this abort_if_linux_arm64?

**Comment by brendongo** [comment] 2023-01-03 07:32
We added it since we do not publish a version that works on linux arm64 nor did we publish a docker image that runs in arm64. The reason we needed a specific call out was installing with pypi on a linux arm64 downloads the x86 binary and prints out a confusing stacktrace when it doesn't work

It does make sense to not print this out if user is building from source.

**Comment by juju4** [comment] 2023-01-08 17:10
This affects pre-commit hook.
Wrapper code should validate architecture and skip test if architecture is not supported.

```
$ pre-commit run -a semgrep
Semgrep Python...........................................................Failed
- hook id: semgrep
- exit code: 2

Semgrep rule registry URL is https://semgrep.dev/registry.
Scanning 104 files with 142 python rules.
  0% 0/104 [00:00<?, ?it/s][Errno 8] Exec format error: '/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/bin/semgrep-core'
Traceback (most recent call last):
  File "/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/commands/scan.py", line 837, in scan
    ) = semgrep.semgrep_main.main(
  File "/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 424, in main
    ) = run_rules(
[...]
OSError: [Errno 8] Exec format error: '/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/bin/semgrep-core'
[...]
$ file /home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/bin/semgrep-core
/home/user/.cache/pre-commit/repoujx6qqwm/py_env-python3/lib/python3.9/site-packages/semgrep/bin/semgrep-core: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

**Comment by caglarsayin** [comment] 2023-01-24 17:28
Is it really that hard?

**Comment by disposedtrolley** [comment] 2023-01-29 23:42
Thanks for the update @brendongo! Are you able to share any specific issues around arm64 support?

**Comment by caglarsayin** [comment] 2023-01-31 15:20
There is no pip wheel for ARM64 Linux machines. Can you please add it to pypi? I was going to offer to build and put it but it is better and safer and more secure, if you put it. whenever I need to use semgrep on linux I need to build it use docker.

**Comment by sonikro** [comment] 2023-03-09 03:51
I developed a DevContainer Feature for Semgrep. Which uses pipx to install the Semgrep binary. However, if users are MacOs users with Apple Sillicon (or anyone else using arm64), they can't use the feature, because since devcontainers run in Linux containers, Semgrep will not be compatible.

I know MacOS users can install the Mac binary, but if a project is using devcontainers to make the developer experience more homogeneous between windows/linux/macos users, it ends up being necessary to have Semgrep run in Linux ARM64. I'm tracking that dependency here https://github.com/sonikro/devcontainer-features/issues/2.

**Comment by clemlesne** [comment] 2023-04-06 10:27
Feature would be much appreciated. ARM64 machines are way cheaper on the cloud. This can reduce the total cost of ownership for teams.

**Comment by inurfuture** [comment] 2023-04-11 03:23
I compiled semgrep-core on the centos7 arrch64 version, which relies on glibc version 2.18

semgrep-core version: 1.17.1

If needed, I can provide it.

**Comment by sfc-gh-hpathak** [comment] 2023-04-21 03:53
@inurfuture could you please? Or share the steps to make it run on centOS7?

**Comment by inurfuture** [comment] 2023-04-25 06:39
> @inurfuture could you please? Or share the steps to make it run on centOS7?

I've emailed semgrep and put the binaries in my repository

**Comment by caglarsayin** [comment] 2023-04-25 13:51
I cannot believe that they are that slow on putting one binary to pypi 👎

**Comment by ievans** [comment] 2023-05-15 20:01
You can check out @inurfuture's build (https://github.com/inurfuture/semgrep-arm) but please note that we cannot vouch for the security or reproducibility of those binaries, therefore can't publish them to pypi. 

We have recently made some progress on this issue -- the returntocorp/ocaml docker image is now being published with support for both amd64 and arm64 architectures, which was an important pre-requisite. But it is hasn't been prioritized yet. Cc @tpetr

**Comment by iosifache** [comment] 2023-06-11 08:11
Hey all 👋🏿,

Here are the steps that I followed to build Semgrep on an Ubuntu 22.04 VM running on Apple M2:

1. Download the repository: `git clone https://github.com/returntocorp/semgrep`
2. Set up the development environment: `make dev-setup`
3. Install `opam`
	
	```
	apt-get install opam
	opam init
	eval $(opam config env)
	```

4. Build: `make`
5. Install `pipenv`: `sudo apt install pipenv`
6. Downgrade `ruamel.yaml` to `0.16.0`: `pip install 'ruamel.yaml==0.16.0'`
7. Install Semgrep's CLI
	
	```
	cd cli
	python setup.py install
	```

**Comment by tpetr** [comment] 2023-07-07 22:20
We are now publishing multi-arch Docker images (linux/amd64 + linux/arm64) for Semgrep 1.31.2 and beyond. We aren’t yet publishing Linux ARM Python wheels to PyPI, but I intend to fix this in the near future.

**Comment by tpetr** [comment] 2023-09-04 21:32
We've been publishing aarch64 Python wheels since 1.33.1, but we were mistakenly only supporting glibc systems due to the `manylinux2014` platform compatibility tag. We now target both `manylinux2014` and `musllinux_1_0` (libmusl AKA Alpine docker images) as of 1.38.0.

**Closed as completed by tpetr** 2023-09-04 21:32 UTC
Labels: enhancement, priority:low, devops, core

**Comment by caglarsayin** [comment] 2023-09-12 11:03
Thank you
