### ISSUE TITLE
poetry install on mac-os distributes ELF binary

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4668] opened 2022-02-14 18:53 UTC
**Describe the bug**

On Max OS:

```
poetry add semgrep
poetry run /path/to/semgrep-core
```
yields:
```
Exec format error
```

Running:
```
file /path/to/semgrep-core
```
yields
```
ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```
which is not a Mac-compatible binary

**Expected behavior**
`pip install semgrep` on Mac should install a Mac-compatible binary

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment

This is using poetry 1.14

**Comment by r2c-demo** [comment] 2022-02-14 18:55
This issue is synced in Linear at https://linear.app/r2c/issue/PA-866/pypi-install-on-mac-os-distributes-elf-binary.

**Comment by nbrahms** [comment] 2022-02-14 19:04
note: running
```
pip uninstall semgrep
pip install semgrep
```
from _within_ the poetry shell fixes the issue

**Comment by brendongo** [comment] 2022-02-14 19:04
Similar to https://github.com/returntocorp/semgrep/issues/2402

**Comment by brendongo** [comment] 2022-02-14 19:06
Hmm unable to reproduce with poetry `Poetry version 1.1.12`

**Comment by nbrahms** [comment] 2022-02-14 19:53
@brendongo I imagine global python and pip versions might matter. I'm using:

```
➜  ~ python3 -m pip --version
pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
➜  ~ python3 --version
Python 3.9.10
```

**Comment by p4p3r** [comment] 2022-05-03 15:14
@nbrahms workaround doesn't work for me...

**Comment by aryx** [comment] 2022-06-21 14:02
Is this fixed now @brendongo since we supported mac M1?

**Comment by brendongo** [comment] 2022-07-01 18:42
This seems like a poetry/pip issue not a semgrep issue.

**Closed as completed by brendongo** 2022-07-01 18:42 UTC
Labels: bug, priority:low, devops, feature:pypi
