### ISSUE TITLE
Semgrep fails with "circular import" error

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#952] opened 2020-06-09 22:01 UTC
**Describe the bug**
When running within `incubator-superset`'s `superset` directory, the following error is thrown:

```bash
$ semgrep --config=https://semgrep.live/c/p/python
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 11, in <module>
    load_entry_point('semgrep==0.9.0', 'console_scripts', 'semgrep')()
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/semgrep/__main__.py", line 4, in <module>
    from semgrep.cli import cli
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/semgrep/cli.py", line 7, in <module>
    import semgrep.config_resolver
  File "/usr/local/Cellar/semgrep/0.9.0/libexec/lib/python3.8/site-packages/semgrep/config_resolver.py", line 7, in <module>
    from typing import Any
  File "/Users/luke/git/tmp/incubator-superset/superset/typing.py", line 17, in <module>
    from typing import Any, Callable, Dict, List, Optional, Tuple, Union
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (/Users/luke/git/tmp/incubator-superset/superset/typing.py)
```

**To Reproduce**
```
$ git clone git@github.com:apache/incubator-superset.git
$ cd incubator/superset
$ semgrep --config=https://semgrep.live/c/p/python
```

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

Mac OSX, Semgrep 0.9.0

**Comment by brendongo** [comment] 2020-06-10 18:43
I can't reproduce this locally with 0.9.0 or 0.10.0. How was your semgrep installed?

**Comment by ievans** [comment] 2020-06-11 21:05
Also can't reproduce this with 0.10.1. Closing for now.

**Closed as completed by ievans** 2020-06-11 21:05 UTC
Labels: bug, lang:python, cannot-reproduce, feature:cli-ux
