### ISSUE TITLE
Cant run semgrep on a specific file

### ISSUE THREAD

**Issue by neonlyis** [semgrep/semgrep#3557] opened 2021-07-20 12:46 UTC
Hello, I want to run semgrep on pypi packages, or test files but dont seem to understand how to do it.
I ran this on my VM:
docker run --rm -v "/root:/mnt" returntocorp/semgrep --config=p/gitlab-bandit --config=p/python /mnt/test.txt

my packages and files are on /root on my VM, after i run this, I get this error:
PermissionError: [Errno 13] Permission denied: '/mnt/test.txt'

when I run:
docker run --rm -v "/root:/mnt" returntocorp/semgrep --config=p/gitlab-bandit --config=p/python *

I get this error:
File not found: test.txt
File not found: anaconda-ks.cfg
ran 106 rules on 0 files: 0 findings

How can I run semgrep on files that I provide?

**Comment by neonlyis** [comment] 2021-07-26 10:53
What does the assignment and label mean? Is this not a feature?

**Comment by brendongo** [comment] 2021-09-15 19:47
Sorry I think this issue fell through the cracks. @neonlyis I can't reproduce what you are running into. Are you sure /root/test.txt exits?

``` docker run --rm -v "$(pwd):/mnt" returntocorp/semgrep --config=p/gitlab-bandit  /mnt``` at the root of this project works. Maybe there is some permission issue with your VM? Can you try running this not on /root?

**Comment by brendongo** [comment] 2021-10-20 23:57
Closing as cannot reproduce

**Closed as completed by brendongo** 2021-10-20 23:57 UTC
Labels: cannot-reproduce, feature:docker
