### ISSUE TITLE
Add a parsing --timeout

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#812] opened 2020-05-21 17:39 UTC
Currently semgrep has a hard-coded timeout for giving up on parsing files (per-file basis). We should make this a user-configurable option and have the python CLI set the default. Suggestion: --timeout=5 gives a 5 second timeout for parsing.

**Comment by nbrahms** [comment] 2020-05-26 17:22
cc. @brendongo for release planning

**Comment by brendongo** [comment] 2020-07-30 21:25
Duplicate of https://github.com/returntocorp/semgrep/issues/1368 and handled in #1385

**Closed as completed by brendongo** 2020-07-30 21:25 UTC
Labels: enhancement
