### ISSUE TITLE
Oldest version semgrep inside container 

### ISSUE THREAD

**Issue by apxitekt0r** [semgrep/semgrep#9924] opened 2024-03-12 23:23 UTC
Hi, maybe someone knows how to decide this problem.
When I install semgrep with the command ```python3 -m pip install semgrep``` inside the docker container and check the version, semgrep shows me oldest version with text:
> A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
> 
> Versions prior to 1.31.0 are no longer supported by Semgrep.dev, please upgrad.
> 0.117.0

The base image for own docker container is Ubuntu 22.04.
When I installing the semgrep with same command on desktop OS i see actual version.

**Comment by kopecs** [comment] 2024-03-14 21:42
Can you share more details about the docker container you're running into this with? I cannot reproduce the issue as described.

**Comment by apxitekt0r** [comment] 2024-03-18 10:51
```
# base image
FROM ubuntu:22.04

# install python
RUN apt-get install -y\
    python3\
    python3-pip

# install semgrep
RUN python3 -m pip install semgrep
```

> docker build --no-cache . -t \<imagename:tag\>

This is an example of my Dockerfile and how i build it.

And result
![Screenshot from 2024-03-18 13-50-39](https://github.com/semgrep/semgrep/assets/36531246/77bea49d-8a98-4ac3-9211-3826992395e7)

upd: logs for example 

```
#15 [12/17] RUN python3 -m pip install semgrep
#15 2.007 Collecting semgrep
#15 2.482   Downloading semgrep-1.66.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl (27.0 MB)
#15 3.766      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.0/27.0 MB 20.6 MB/s eta 0:00:00
#15 3.931 Collecting typing-extensions~=4.2
#15 3.981   Downloading typing_extensions-4.10.0-py3-none-any.whl (33 kB)
#15 4.105 Collecting attrs>=21.3
#15 4.156   Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
#15 4.171      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 KB 4.9 MB/s eta 0:00:00
#15 4.362 Collecting colorama~=0.4.0
#15 4.406   Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
#15 4.595 Collecting urllib3~=2.0
#15 4.640   Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
#15 4.664      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 KB 5.5 MB/s eta 0:00:00
#15 4.772 Collecting glom~=22.1
#15 4.833   Downloading glom-22.1.0-py2.py3-none-any.whl (100 kB)
#15 4.848      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.7/100.7 KB 8.6 MB/s eta 0:00:00
#15 4.951 Collecting defusedxml~=0.7.1
#15 4.997   Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
#15 5.139 Collecting peewee~=3.14
#15 5.187   Downloading peewee-3.17.1.tar.gz (3.0 MB)
#15 5.317      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 23.6 MB/s eta 0:00:00
#15 5.764   Installing build dependencies: started
#15 12.57   Installing build dependencies: finished with status 'done'
#15 12.58   Getting requirements to build wheel: started
#15 12.94   Getting requirements to build wheel: finished with status 'done'
#15 12.94   Preparing metadata (pyproject.toml): started
#15 13.20   Preparing metadata (pyproject.toml): finished with status 'done'
#15 13.33 Collecting tomli~=2.0.1
#15 13.37   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
#15 14.06 Collecting ruamel.yaml<0.18,>=0.16.0
#15 14.12   Downloading ruamel.yaml-0.17.40-py3-none-any.whl (113 kB)
#15 14.14      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.7/113.7 KB 5.5 MB/s eta 0:00:00
#15 14.28 Collecting jsonschema~=4.6
#15 14.33   Downloading jsonschema-4.21.1-py3-none-any.whl (85 kB)
#15 14.34      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 KB 7.5 MB/s eta 0:00:00
#15 14.44 Collecting wcmatch~=8.3
#15 14.49   Downloading wcmatch-8.5.1-py3-none-any.whl (39 kB)
#15 14.60 Collecting exceptiongroup~=1.2.0
#15 14.65   Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
#15 14.77 Collecting click~=8.1
#15 14.81   Downloading click-8.1.7-py3-none-any.whl (97 kB)
#15 14.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 KB 8.8 MB/s eta 0:00:00
#15 14.92 Collecting boltons~=21.0
#15 14.97   Downloading boltons-21.0.0-py2.py3-none-any.whl (193 kB)
#15 14.99      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.7/193.7 KB 16.0 MB/s eta 0:00:00
#15 15.22 Collecting rich>=12.6.0
#15 15.26   Downloading rich-13.7.1-py3-none-any.whl (240 kB)
#15 15.29      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.7/240.7 KB 10.5 MB/s eta 0:00:00
#15 15.45 Collecting requests~=2.22
#15 15.49   Downloading requests-2.31.0-py3-none-any.whl (62 kB)
#15 15.51      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 KB 2.9 MB/s eta 0:00:00
#15 15.66 Collecting packaging>=21.0
#15 15.71   Downloading packaging-24.0-py3-none-any.whl (53 kB)
#15 15.73      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 KB 2.4 MB/s eta 0:00:00
#15 15.83 Collecting click-option-group~=0.5
#15 15.88   Downloading click_option_group-0.5.6-py3-none-any.whl (12 kB)
#15 16.07 Collecting face>=20.1.0
#15 16.12   Downloading face-22.0.0-py3-none-any.whl (54 kB)
#15 16.13      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 KB 4.2 MB/s eta 0:00:00
#15 16.93 Collecting rpds-py>=0.7.1
#15 16.98   Downloading rpds_py-0.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
#15 17.03      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.8 MB/s eta 0:00:00
#15 17.16 Collecting jsonschema-specifications>=2023.03.6
#15 17.20   Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
#15 17.46 Collecting referencing>=0.28.4
#15 17.50   Downloading referencing-0.34.0-py3-none-any.whl (26 kB)
#15 17.68 Collecting certifi>=2017.4.17
#15 17.73   Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
#15 17.76      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 KB 7.1 MB/s eta 0:00:00
#15 17.87 Collecting idna<4,>=2.5
#15 17.92   Downloading idna-3.6-py3-none-any.whl (61 kB)
#15 17.93      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 KB 5.1 MB/s eta 0:00:00
#15 18.33 Collecting charset-normalizer<4,>=2
#15 18.38   Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
#15 18.40      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 KB 7.1 MB/s eta 0:00:00
#15 18.54 Collecting pygments<3.0.0,>=2.13.0
#15 18.59   Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
#15 18.63      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 26.7 MB/s eta 0:00:00
#15 18.77 Collecting markdown-it-py>=2.2.0
#15 18.82   Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
#15 18.83      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 KB 6.9 MB/s eta 0:00:00
#15 19.05 Collecting ruamel.yaml.clib>=0.2.7
#15 19.09   Downloading ruamel.yaml.clib-0.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (526 kB)
#15 19.13      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.7/526.7 KB 16.0 MB/s eta 0:00:00
#15 19.26 Collecting bracex>=2.1.1
#15 19.31   Downloading bracex-2.4-py3-none-any.whl (11 kB)
#15 19.51 Collecting mdurl~=0.1
#15 19.56   Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
#15 19.65 Building wheels for collected packages: peewee
#15 19.65   Building wheel for peewee (pyproject.toml): started
#15 20.02   Building wheel for peewee (pyproject.toml): finished with status 'done'
#15 20.02   Created wheel for peewee: filename=peewee-3.17.1-py3-none-any.whl size=136906 sha256=1015bcb4d69e4e6c2355519ba3a82765be3a451908cf8df4943606097da0e110
#15 20.02   Stored in directory: /root/.cache/pip/wheels/d7/35/5c/1374782be033462df5f40174d8d879519d64ed8c25a1977554
#15 20.03 Successfully built peewee
#15 20.25 Installing collected packages: peewee, boltons, urllib3, typing-extensions, tomli, ruamel.yaml.clib, rpds-py, pygments, packaging, mdurl, idna, face, exceptiongroup, defusedxml, colorama, click, charset-normalizer, certifi, bracex, attrs, wcmatch, ruamel.yaml, requests, referencing, markdown-it-py, glom, click-option-group, rich, jsonschema-specifications, jsonschema, semgrep
#15 24.06 Successfully installed attrs-23.2.0 boltons-21.0.0 bracex-2.4 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 click-option-group-0.5.6 colorama-0.4.6 defusedxml-0.7.1 exceptiongroup-1.2.0 face-22.0.0 glom-22.1.0 idna-3.6 jsonschema-4.21.1 jsonschema-specifications-2023.12.1 markdown-it-py-3.0.0 mdurl-0.1.2 packaging-24.0 peewee-3.17.1 pygments-2.17.2 referencing-0.34.0 requests-2.31.0 rich-13.7.1 rpds-py-0.18.0 ruamel.yaml-0.17.40 ruamel.yaml.clib-0.2.8 semgrep-1.66.0 tomli-2.0.1 typing-extensions-4.10.0 urllib3-2.2.1 wcmatch-8.5.1
#15 24.06 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#15 DONE 24.5s
```

**Comment by apxitekt0r** [comment] 2024-03-20 22:09
In logs installed last version (on date when i wrote this comment) but after run image to check version, semgrep return message about old version

**Comment by kopecs** [comment] 2024-03-20 23:50
Your dockerfile fails to build for me due to the lack of a package cache. I can build it if I add `apt-get update`, but I cannot reproduce the version warning.

**Comment by apxitekt0r** [comment] 2024-03-21 15:13
Maybe this host OS bug... I'll try to repeat it on another host OS to check what will happen.

**Comment by apxitekt0r** [comment] 2024-03-24 21:17
I repeated to build image in another host OS and see the same results. If you build like in my configuration I think you will see the same results.

**Comment by apxitekt0r** [comment] 2024-05-22 09:40
> Your dockerfile fails to build for me due to the lack of a package cache. I can build it if I add `apt-get update`, but I cannot reproduce the version warning.

Hi i trying again and again build own semgrep image but i see this message yet. i tried use another base image but seen same result. can you share your version where we tried to repeat my way?


prof where installed version is right but when i try use semgrep i see message about old version
```
#16 [12/23] RUN python3 -m pip install --upgrade pip
#16 0.941 Requirement already satisfied: pip in /usr/lib/python3/dist-packages (22.0.2)
#16 1.785 Collecting pip
#16 2.463   Downloading pip-24.0-py3-none-any.whl (2.1 MB)
#16 2.956      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 4.3 MB/s eta 0:00:00
#16 2.976 Installing collected packages: pip
#16 2.976   Attempting uninstall: pip
#16 2.977     Found existing installation: pip 22.0.2
#16 2.978     Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
#16 2.979     Can't uninstall 'pip'. No files were found to uninstall.
#16 4.412 Successfully installed pip-24.0
#16 4.412 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#16 DONE 4.7s

#17 [13/23] RUN python3 -m pip install semgrep
#17 2.050 Collecting semgrep
#17 2.550   Downloading semgrep-1.73.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl.metadata (19 kB)
#17 2.722 Collecting attrs>=21.3 (from semgrep)
#17 2.961   Downloading attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
#17 3.103 Collecting boltons~=21.0 (from semgrep)
#17 3.146   Downloading boltons-21.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
#17 3.267 Collecting click-option-group~=0.5 (from semgrep)
#17 3.310   Downloading click_option_group-0.5.6-py3-none-any.whl.metadata (8.3 kB)
#17 3.454 Collecting click~=8.1 (from semgrep)
#17 3.496   Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
#17 3.629 Collecting colorama~=0.4.0 (from semgrep)
#17 3.671   Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
#17 3.805 Collecting defusedxml~=0.7.1 (from semgrep)
#17 3.847   Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB)
#17 3.985 Collecting exceptiongroup~=1.2.0 (from semgrep)
#17 4.031   Downloading exceptiongroup-1.2.1-py3-none-any.whl.metadata (6.6 kB)
#17 4.149 Collecting glom~=22.1 (from semgrep)
#17 4.195   Downloading glom-22.1.0-py2.py3-none-any.whl.metadata (4.9 kB)
#17 4.364 Collecting jsonschema~=4.6 (from semgrep)
#17 4.405   Downloading jsonschema-4.22.0-py3-none-any.whl.metadata (8.2 kB)
#17 4.542 Collecting packaging>=21.0 (from semgrep)
#17 4.583   Downloading packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
#17 4.726 Collecting peewee~=3.14 (from semgrep)
#17 4.771   Downloading peewee-3.17.5.tar.gz (3.0 MB)
#17 5.027      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 11.7 MB/s eta 0:00:00
#17 5.271   Installing build dependencies: started
#17 8.738   Installing build dependencies: finished with status 'done'
#17 8.740   Getting requirements to build wheel: started
#17 9.033   Getting requirements to build wheel: finished with status 'done'
#17 9.037   Preparing metadata (pyproject.toml): started
#17 9.369   Preparing metadata (pyproject.toml): finished with status 'done'
#17 9.526 Collecting requests~=2.22 (from semgrep)
#17 9.567   Downloading requests-2.32.2-py3-none-any.whl.metadata (4.6 kB)
#17 9.831 Collecting rich>=12.6.0 (from semgrep)
#17 9.873   Downloading rich-13.7.1-py3-none-any.whl.metadata (18 kB)
#17 10.33 Collecting ruamel.yaml<0.18,>=0.16.0 (from semgrep)
#17 10.37   Downloading ruamel.yaml-0.17.40-py3-none-any.whl.metadata (19 kB)
#17 10.51 Collecting tomli~=2.0.1 (from semgrep)
#17 10.55   Downloading tomli-2.0.1-py3-none-any.whl.metadata (8.9 kB)
#17 10.68 Collecting typing-extensions~=4.2 (from semgrep)
#17 10.72   Downloading typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
#17 10.96 Collecting urllib3~=2.0 (from semgrep)
#17 11.01   Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
#17 11.16 Collecting wcmatch~=8.3 (from semgrep)
#17 11.20   Downloading wcmatch-8.5.2-py3-none-any.whl.metadata (4.8 kB)
#17 11.41 Collecting face>=20.1.0 (from glom~=22.1->semgrep)
#17 11.46   Downloading face-22.0.0-py3-none-any.whl.metadata (816 bytes)
#17 11.61 Collecting jsonschema-specifications>=2023.03.6 (from jsonschema~=4.6->semgrep)
#17 11.66   Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl.metadata (3.0 kB)
#17 11.87 Collecting referencing>=0.28.4 (from jsonschema~=4.6->semgrep)
#17 11.91   Downloading referencing-0.35.1-py3-none-any.whl.metadata (2.8 kB)
#17 12.38 Collecting rpds-py>=0.7.1 (from jsonschema~=4.6->semgrep)
#17 12.42   Downloading rpds_py-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
#17 12.71 Collecting charset-normalizer<4,>=2 (from requests~=2.22->semgrep)
#17 12.75   Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
#17 12.88 Collecting idna<4,>=2.5 (from requests~=2.22->semgrep)
#17 12.92   Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
#17 13.09 Collecting certifi>=2017.4.17 (from requests~=2.22->semgrep)
#17 13.13   Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
#17 13.29 Collecting markdown-it-py>=2.2.0 (from rich>=12.6.0->semgrep)
#17 13.33   Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
#17 13.49 Collecting pygments<3.0.0,>=2.13.0 (from rich>=12.6.0->semgrep)
#17 13.53   Downloading pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
#17 13.82 Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml<0.18,>=0.16.0->semgrep)
#17 13.86   Downloading ruamel.yaml.clib-0.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (2.2 kB)
#17 14.03 Collecting bracex>=2.1.1 (from wcmatch~=8.3->semgrep)
#17 14.07   Downloading bracex-2.4-py3-none-any.whl.metadata (3.6 kB)
#17 14.29 Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=12.6.0->semgrep)
#17 14.34   Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
#17 14.49 Downloading semgrep-1.73.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-any.whl (27.6 MB)
#17 15.66    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.6/27.6 MB 17.5 MB/s eta 0:00:00
#17 15.71 Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
#17 15.73    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 2.0 MB/s eta 0:00:00
#17 15.78 Downloading boltons-21.0.0-py2.py3-none-any.whl (193 kB)
#17 15.81    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.7/193.7 kB 6.5 MB/s eta 0:00:00
#17 15.85 Downloading click-8.1.7-py3-none-any.whl (97 kB)
#17 15.88    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 3.4 MB/s eta 0:00:00
#17 15.92 Downloading click_option_group-0.5.6-py3-none-any.whl (12 kB)
#17 15.99 Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
#17 16.06 Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
#17 16.18 Downloading exceptiongroup-1.2.1-py3-none-any.whl (16 kB)
#17 16.25 Downloading glom-22.1.0-py2.py3-none-any.whl (100 kB)
#17 16.28    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.7/100.7 kB 3.3 MB/s eta 0:00:00
#17 16.38 Downloading jsonschema-4.22.0-py3-none-any.whl (88 kB)
#17 16.42    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 2.4 MB/s eta 0:00:00
#17 16.47 Downloading packaging-24.0-py3-none-any.whl (53 kB)
#17 16.49    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 2.4 MB/s eta 0:00:00
#17 16.54 Downloading requests-2.32.2-py3-none-any.whl (63 kB)
#17 16.57    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 kB 2.2 MB/s eta 0:00:00
#17 16.63 Downloading rich-13.7.1-py3-none-any.whl (240 kB)
#17 16.67    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.7/240.7 kB 8.0 MB/s eta 0:00:00
#17 16.71 Downloading ruamel.yaml-0.17.40-py3-none-any.whl (113 kB)
#17 16.73    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 113.7/113.7 kB 5.0 MB/s eta 0:00:00
#17 16.80 Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
#17 16.87 Downloading typing_extensions-4.11.0-py3-none-any.whl (34 kB)
#17 16.93 Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
#17 16.97    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.1/121.1 kB 4.0 MB/s eta 0:00:00
#17 17.01 Downloading wcmatch-8.5.2-py3-none-any.whl (39 kB)
#17 17.09 Downloading bracex-2.4-py3-none-any.whl (11 kB)
#17 17.16 Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
#17 17.19    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.8/163.8 kB 5.3 MB/s eta 0:00:00
#17 17.24 Downloading charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
#17 17.26    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 142.1/142.1 kB 5.8 MB/s eta 0:00:00
#17 17.31 Downloading face-22.0.0-py3-none-any.whl (54 kB)
#17 17.34    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 1.7 MB/s eta 0:00:00
#17 17.39 Downloading idna-3.7-py3-none-any.whl (66 kB)
#17 17.42    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 2.2 MB/s eta 0:00:00
#17 17.46 Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
#17 17.53 Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
#17 17.56    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 2.8 MB/s eta 0:00:00
#17 17.61 Downloading pygments-2.18.0-py3-none-any.whl (1.2 MB)
#17 17.67    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 22.4 MB/s eta 0:00:00
#17 17.71 Downloading referencing-0.35.1-py3-none-any.whl (26 kB)
#17 17.79 Downloading rpds_py-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
#17 17.85    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 20.8 MB/s eta 0:00:00
#17 17.89 Downloading ruamel.yaml.clib-0.2.8-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (526 kB)
#17 17.93    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.7/526.7 kB 14.4 MB/s eta 0:00:00
#17 17.98 Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
#17 18.11 Building wheels for collected packages: peewee
#17 18.11   Building wheel for peewee (pyproject.toml): started
#17 18.51   Building wheel for peewee (pyproject.toml): finished with status 'done'
#17 18.52   Created wheel for peewee: filename=peewee-3.17.5-py3-none-any.whl size=138635 sha256=565b94c71221a4b868595b18dd6a33bce8a363e243aa714ac6498169bfd38749
#17 18.52   Stored in directory: /root/.cache/pip/wheels/06/80/9b/98db0d58349a2f5c09f8406789ade4270762f97b7d26f2fa22
#17 18.52 Successfully built peewee
#17 18.67 Installing collected packages: peewee, boltons, urllib3, typing-extensions, tomli, ruamel.yaml.clib, rpds-py, pygments, packaging, mdurl, idna, face, exceptiongroup, defusedxml, colorama, click, charset-normalizer, certifi, bracex, attrs, wcmatch, ruamel.yaml, requests, referencing, markdown-it-py, glom, click-option-group, rich, jsonschema-specifications, jsonschema, semgrep
#17 22.91 Successfully installed attrs-23.2.0 boltons-21.0.0 bracex-2.4 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 click-option-group-0.5.6 colorama-0.4.6 defusedxml-0.7.1 exceptiongroup-1.2.1 face-22.0.0 glom-22.1.0 idna-3.7 jsonschema-4.22.0 jsonschema-specifications-2023.12.1 markdown-it-py-3.0.0 mdurl-0.1.2 packaging-24.0 peewee-3.17.5 pygments-2.18.0 referencing-0.35.1 requests-2.32.2 rich-13.7.1 rpds-py-0.18.1 ruamel.yaml-0.17.40 ruamel.yaml.clib-0.2.8 semgrep-1.73.0 tomli-2.0.1 typing-extensions-4.11.0 urllib3-2.2.1 wcmatch-8.5.2
#17 22.91 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#17 DONE 23.5s
```
i don't have this issue with another packages in python in docker.

In strace:
```
openat(AT_FDCWD, "/root/.cache/semgrep_version", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 5
newfstatat(5, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
ioctl(5, TCGETS, 0x7fff4dff8360)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(5, 0, SEEK_CUR)                   = 0
ioctl(5, TCGETS, 0x7fff4dff81b0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(5, 0, SEEK_CUR)                   = 0
write(5, "1716398497\n{\"latest\": \"1.73.0\", "..., 658) = 658
close(5)                                = 0
getpid()                                = 9
write(2, "\nA new version of Semgrep is ava"..., 79
A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
) = 79
write(3, "2024-05-22 17:21:37,310 - semgre"..., 137) = 137
getpid()                                = 9
write(2, "\nVersions prior to 1.31.0 are no"..., 82
Versions prior to 1.31.0 are no longer supported by Semgrep.dev, please upgrade.
) = 82
write(3, "2024-05-22 17:21:37,310 - semgre"..., 140) = 140
getpid()                                = 9
write(3, "2024-05-22 17:21:37,311 - semgre"..., 151) = 151
write(1, "0.117.0\n", 80.117.0
)                = 8
close(4)                                = 0
close(3)            
```

**Comment by emjin** [comment] 2024-05-22 21:34
I got the same result as @kopecs. I first ran:
```
# base image
FROM ubuntu:22.04

# install python
RUN apt-get install -y\
    python3\
    python3-pip

# install semgrep
RUN python3 -m pip install semgrep
```

by placing that in a Dockerfile and running `docker build -t github_bug .`. This didn't work. I then updated the Dockerfile to:

```
# base image
FROM ubuntu:22.04

# install python
RUN apt-get update
RUN apt-get install -y\
    python3\
    python3-pip

# install semgrep
RUN python3 -m pip install semgrep
```

which built successfully. Using that built image, I ran:
```
docker run -t github_bug semgrep --version
```

which gave me `1.73.0`.

I'm closing this since I can't reproduce.

**Comment by apxitekt0r** [comment] 2024-05-22 22:11
@emjin yes its work. I think something another do this bug when i install other application. You can close this issue

**Closed as completed** 2024-05-22 22:17 UTC
Labels: cannot-reproduce, devops

**Comment by apxitekt0r** [comment] 2024-05-22 23:08
@emjin i found conflict when install mobsf and semgrep in one image. I think I don't need to reopen this issue but you can check it.
