### ISSUE TITLE
A single identifier pattern does not match a field name

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1776] opened 2020-10-02 23:42 UTC
**Describe the bug**
Attempting to find a keyword inside a function using pattern inside should match. There is some inconsistent behavior depending on whether the keyword is an  object or a function. 

**To Reproduce**
If the keyword is a function, there is no match.
https://dev.semgrep.dev/s/l0KL/

If the keyword is an object, there is a match.
https://semgrep.dev/s/X2yw/

**Expected behavior**
I would expect both of these to produce matches.

**Comment by aryx** [comment] 2020-10-06 19:03
A keyword in programming languages is 'if', 'then', but not group_by. This is an identifier.
And the issue here is that in the pattern, group_by is parsed as an identifier (Id in the generic AST), but
in the code it is parsed as a fieldname (probably a FId), and so it is not matched.
We could change that and allow a single ID to match a field ID.
But the issue is not about pattern-inside I think.

**Comment by aryx** [comment] 2020-10-06 19:04
In fact, you will probably get the same issue in other languages, not just Python.

**Comment by aryx** [comment] 2020-10-23 20:06
Semgrep is not grep, so here we think you look for the identifier group_by, but group_by in the code is not a regular identifier,
it's a field name, which have different scoping rules than a regular identifier.
You need to be more precise right now and give more context like https://dev.semgrep.dev/s/Jq8o/
This is debatable, we could allow at some point single identifier like this to also be matched against field name, or keyword argument (we had a similar pb with Go).
But for now I'll mark as wontfix.

**Closed as completed by aryx** 2020-10-23 20:06 UTC
Labels: bug, lang:python, semgrep-is-not-grep
