### ISSUE TITLE
Saved custom rules URLs are behaving strangely

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2442] opened 2021-01-22 04:03 UTC
**Describe the bug**
Not sure if this is related to #2436, but I just discovered that things are very strange.
I created this custom rule in Chrome: https://semgrep.dev/s/msorens:combinelatest-not-combining.
I later went back into Semgrep Live and revised the text, starting to make another new rule, but did not save it again.
Yet, now when I go back to the saved rule URL above, it shows the revised text of that second rule.
Stranger still, when I open it in a different browser, it shows completely different content!

**To Reproduce**
As above; I will experiment more when I have a chance to see how reproducible it is. But I wanted to get this posted ASAP to see if you folks might be seeing it as well.

**Expected behavior**
Saved rule should have re-appeared at that URL.

**Screenshots**
NA

**What is the priority of the bug to you?**
P1 - important

**Environment**

**Comment by aryx** [comment] 2021-01-22 09:02
cc @chmccreery

**Comment by msorens** [comment] 2021-01-22 17:44
Update:
I sat down to try this again and record more carefully what occurred.
I had this from sometime ago--calling this `Rule1`: https://semgrep.dev/s/msorens:test-rule.
Yesterday, I introduced `Rule2` (https://semgrep.dev/s/msorens:combineLatest-not-combining) and observed the problems noted above.

Today as a baseline, I tried `Rule2` again in both Firefox and Chrome after closing and restarting both browsers. The behavior was the same as yesterday: both browsers showed content unrelated to that saved rule and the content of both browsers were different from each other!

(1) I created `Rule3`: https://semgrep.dev/s/msorens:new-rule-test-1
(2) I then opened `Rule2` in both Firefox and in Chrome--and both showed the correct rule content!
(3) I went back to `Rule3` in both Firefox and in Chrome--and both showed the correct rule content.
(4) I edited `Rule3`, re-entered the name and saved it.
(5) I went back to `Rule3` in both Firefox and in Chrome--and both showed the correct rule content.
(6) Added `Rule3` to a policy, then from that policy attempted to open up the rule (Chrome). It showed the correct content. Also note that #2436 did NOT manifest here, so appears that my initial report above was tied to #2436 after all.

➡️ Today I am unable to reproduce either the problem reported here or the problem reported in #2436.
So... probably best to either close this and #2436 or put them on the back burner unless/until something resurfaces.

**Comment by chmccreery** [comment] 2021-01-22 18:23
Thanks @msorens for the detailed report - I am planning to dedicate some time next week to fixing bugs in the editor, and hope I am able to resolve this wonkiness as well. There are some fields like language and rule-name/rule-id that can be populated differently inside and outside the editor, leading to unexpected behaviors, and rule-name is not rendered in the URL as consistently as it should be, so maybe this has to do with that 🤷‍♀️

**Comment by underyx** [comment] 2021-01-26 18:15
Just one more note @msorens: our initial design for this feature was intended to be "flawed" quality, with anything other than the most basic rule saving/updating being out-of-scope. Since this issue involves updating the design of the feature to cover more use cases, we consider it an feature enhancement as opposed to a bug report. This means it'll go on the feature-work track and take weeks to deliver as opposed to the bugfix-work track.

cc @dlukeomalley, consider this for work in the near future

**Comment by msorens** [comment] 2021-01-27 00:40
Thanks for the note, @underyx . While I appreciate your point, I am not quite sure why you are saying this involves updating the design at all. As far as I can see, I really was doing only "the most basic rule saving/updating".

**Comment by chmccreery** [comment] 2021-01-27 02:09
Yep, I agree @msorens, our named-rule saving behaviors have some bugs. I will take a look at this tomorrow, it has been on my list for awhile.

**Comment by chmccreery** [comment] 2021-01-29 01:11
Ok, this is being slated for next week's "feature freeze/bug bash" theme

**Comment by msorens** [comment] 2021-02-02 01:12
I am reasonably sure this has been resolved by the fix to https://github.com/returntocorp/semgrep/issues/2436.

**Comment by underyx** [comment] 2021-02-02 10:20
@msorens I can access the original rule at https://semgrep.dev/s/msorens:combineLatest-not-combining – note the uppercase `L`. Is this the name after your recreation? Is it possible you were trying to open the URL from the issue description which has been lowercased?

**Comment by msorens** [comment] 2021-02-02 15:15
Yes, that is the newly created rule you found, not the original one.

**Comment by chmccreery** [comment] 2021-02-02 18:27
OK, @msorens feel free to close this issue if it was in fact resolved by #2436

**Closed as completed** 2021-02-03 15:10 UTC
Labels: enhancement, priority:medium, user:external, feature:editor, ux
