### ISSUE TITLE
No File Info Yet exn on toyota benchmarks C codebase

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#1412] opened 2020-07-30 20:14 UTC
**Describe the bug**
Error message:
```
01.w_Defects$ semgrep --config "https://semgrep.live/p/Ascof22.Ascof22.Espresso-IT_C_rules_only" .
using config from https://semgrep.live/p/Ascof22.Ascof22.Espresso-IT_C_rules_only. Visit https://semgrep.live/registry to see all public rules.
downloading config...
running 7 rules...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|7/7
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 33, in <module>
    sys.exit(load_entry_point('semgrep==0.16.0', 'console_scripts', 'semgrep')())
  File "/usr/local/Cellar/semgrep/0.16.0/libexec/lib/python3.8/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/Cellar/semgrep/0.16.0/libexec/lib/python3.8/site-packages/semgrep/cli.py", line 321, in cli
    semgrep.semgrep_main.main(
  File "/usr/local/Cellar/semgrep/0.16.0/libexec/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 355, in main
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/usr/local/Cellar/semgrep/0.16.0/libexec/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 355, in <listcomp>
    semgrep_errors = [e.into_semgrep_error() for e in semgrep_core_errors]
  File "/usr/local/Cellar/semgrep/0.16.0/libexec/lib/python3.8/site-packages/semgrep/core_exception.py", line 69, in into_semgrep_error
    with open(self._path, errors="replace") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'NO FILE INFO YET'
```

**To Reproduce**
Running [this pack of C community rules](https://semgrep.live/p/Ascof22.Ascof22.Espresso-IT_C_rules_only) on the [static analysis benchmarks from Toyota ITC](https://github.com/regehr/itc-benchmarks/) on macOS High Sierra 10.13.6.

**Expected behavior**
semgrep should be able to run without errors.

**Environment**
macOS High Sierra 10.13.6

**Comment by sabrinabrogren** [comment] 2020-07-30 20:33
@aryx perhaps this has to do with these:
https://github.com/returntocorp/pfff/commit/1784a99ff1ce0b12f508998ba6364fa83972ffa7
https://github.com/returntocorp/pfff/commit/407fd16cae58d50c4a5f5af5910ecf54715afe17

**Comment by aryx** [comment] 2020-08-06 12:19
I don't see how PRs for Ruby could be related to analyzing a C repository.
The "NO FILE INFO YET" error usually happens when we tokenize a file and forget to call the function
tokenize_all_and_adjust_pos which adjust the filename and line/col information for each tokens.
Not sure why it triggers here.
You can run with SEMGREP_CORE_EXTRA=-debug  to at least see the offending file in the ITC benchmark repo.

**Comment by nbrahms** [comment] 2020-08-10 17:34
Could be a duplicate of #735

**Comment by aryx** [comment] 2020-08-31 14:17
Also I don't think the issue title is very good. I don't think it has anything to do with macOS sierra.

**Comment by sabrinabrogren** [comment] 2020-08-31 21:06
Feel free to change it! I just wrote something quick when creating the issue and had no idea what was causing it (and I'm still not sure).

**Comment by mschwager** [comment] 2020-11-10 14:49
We're now gracefully handling this error case: https://github.com/returntocorp/semgrep/pull/1999

This error either means Semgrep is running over invalid code, or there's a bug in our parsing. Either way, we shouldn't see `NO FILE INFO YET` anymore after the 0.31.0 release of Semgrep. I'm going to close this issue out, if you see lexical errors please open a new issue with the relevant pattern and code snippet. Thanks!

**Closed as completed by mschwager** 2020-11-10 14:49 UTC
Labels: bug, user:external
