### ISSUE TITLE
Support constant propagation of Terraform variables

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#4816] opened 2022-03-15 21:41 UTC
**Is your feature request related to a problem? Please describe.**
Realistic Terraform code uses variables and other Terraform features that make Semgrep rules reasoning about just the direct text incomplete and/or noisy.

Here's an example of something that shouldn't match but does currently:
https://semgrep.dev/s/clintgibler:azure-storage-use-secure-tls-policy

**Describe the solution you'd like**
I want Semgrep to understand when variables are used in Terraform. 

To be honest, this feature is probably table stakes to being a high quality IaC tool.

**Describe alternatives you've considered**
Potential alternatives:
1. Be OK with the false positives for now.
2. Have a Semgrep pre-processing step that runs `terraform plan` or the like that fully resolves variables/etc. so Semgrep can just analyze the resulting, fully resolved config. 
    * With this approach, Semgrep core wouldn't have to understand how Terraform actually works, which is nice from a simplicity POV. A number of IaC tools do this. 
    * But then we wouldn't strictly be analyzing the source code, we'd be running some supporting tools, so Semgrep users scanning Terraform would need to have Terraform installed, maybe a buildable environment, etc.
3. Teach Semgrep to understand Terraform semantics.

The third option is probably "best," but is also the most work.

**Use case**
High quality analysis of real Terraform code- better TPs and fewer FPs.

**Additional context**
Feature request from community member: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1646095471244789

**Comment by r2c-demo** [comment] 2022-03-15 21:42
This issue is synced in Linear at https://linear.app/r2c/issue/PA-985/support-constant-propagation-in-terraform-variables.

**Comment by aryx** [comment] 2022-03-18 12:21
dupe of: https://github.com/returntocorp/semgrep/issues/1147

**Closed as completed** 2022-03-19 14:32 UTC
Labels: priority:medium, user:external, lang:terraform
