### ISSUE TITLE
Expressions are not found within with statement "contents" if there is no `as` clause

### ISSUE THREAD

**Issue by spookylukey** [semgrep/semgrep#5635] opened 2022-06-27 10:23 UTC
**Describe the bug**

Given the following rule:
```yaml
id: expression-in-with-statement-contents
severity: ERROR
languages:
  - python
patterns:
  - pattern: contextlib.suppress
message: Test
```

I expect all uses of the `contextlib.suppress` to be found. But in the following code, the first usage is found, but the second, in a `with` statement first line is not found:
```python

import contextlib

f = contextlib.suppress(Exception)

with contextlib.suppress(Exception):
    pass
```

See playground link: https://semgrep.dev/playground/s/spookylukey:expression-in-with-statement-contents

It seems that Semgrep only matches things when there is an `as` parameter, which is not needed in this case (and you wouldn't want to add, as it would  trigger other linter errors, like "local variable dummy is assigned to but never used").

See also https://github.com/returntocorp/semgrep/issues/5634

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official binary of latest version, plus Playground

**Use case**
Any code using with statements that don't need an `as` parameter, which is quite a lot.

**Comment by r2c-demo** [comment] 2022-06-27 10:25
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1571/expressions-are-not-found-within-with-statement-contents-if-there-is. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment] 2022-06-27 18:03
Hi, thanks for the bug report(s). Are you able to reproduce this on version 0.100.0? I'm not sure why the playground version is out of date.

I believe this should've gotten fixed by https://github.com/returntocorp/semgrep/pull/5534 and I'm getting (almost) expected matches locally---it looks like we may not be matching the `with` keyword which could cause some issues with autofix, but for matches this shouldn't be too significant an issue.

**Comment by kopecs** [comment] 2022-06-27 21:06
I believe the playground is now updated to 0.100.0 and you should be able to see this working.

**Closed as completed by kopecs** 2022-06-27 21:06 UTC
Labels: lang:python, fixed
