### ISSUE TITLE
Equivalences will sometimes supersede pattern logic

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#652] opened 2020-05-02 00:24 UTC
**Describe the bug**
Using equivalences will sometimes result in findings that should not match the `pattern`.

**To Reproduce**
Eg., it should not fire on the last example.
https://semgrep.live/O67?version=develop

**Comment by brendongo** [comment] 2020-05-18 20:36
Was able to reproduce this issue on semgrep-core

`semgrep-core -lang python -rules_file rules.yaml -equivalences equivalences.yaml target.py`

```
rules:
- id: 0.open-redirect
  pattern: django.shortcuts.redirect(..., request.$W.get(...), ...)
  severity: WARNING
  languages:
  - python
  message: <internalonly>
```

```
equivalences:
- id: open-redirect-0
  languages:
  - python
  pattern: django.shortcuts.redirect(...) <==> django.http.HttpResponseRedirect(...)
```

```
from django.http import HttpResponseRedirect
from django.shortcuts import redirect

def arg(request):
    # ruleid: open-redirect
    return redirect(request.POST.get("url"))


def fine(request):
    # ok
    return redirect("index")

def argh(request):
    # ruleid: open-redirect
    return HttpResponseRedirect(request.POST.get("url"))

def arghhh(request):
    # ok
    return HttpResponseRedirect("index")
```

**Comment by brendongo** [comment] 2020-05-18 20:37
Outputs 
```
{
  "matches": [
    {
      "check_id": "0.open-redirect",
      "path": "target.py",
      "start": { "line": 6, "col": 12, "offset": 141 },
      "end": { "line": 6, "col": 43, "offset": 172 },
      "extra": {
        "message": "<internalonly>",
        "metavars": {
          "$W": {
            "start": { "line": 6, "col": 29, "offset": 158 },
            "end": { "line": 6, "col": 33, "offset": 162 },
            "abstract_content": "POST",
            "unique_id": {
              "type": "AST",
              "md5sum": "604c48cc3c21f55ee2721af1c1e781ef"
            }
          }
        }
      }
    },
    {
      "check_id": "0.open-redirect",
      "path": "target.py",
      "start": { "line": 15, "col": 12, "offset": 293 },
      "end": { "line": 15, "col": 55, "offset": 336 },
      "extra": { "message": "<internalonly>", "metavars": {} }
    },
    {
      "check_id": "0.open-redirect",
      "path": "target.py",
      "start": { "line": 19, "col": 12, "offset": 381 },
      "end": { "line": 19, "col": 40, "offset": 409 },
      "extra": { "message": "<internalonly>", "metavars": {} }
    }
  ],
  "errors": [],
  "stats": { "okfiles": 1, "errorfiles": 0 }
}
```
when it should not fire on line 19

**Comment by aryx** [comment] 2020-05-22 11:30
There's a bug, but you should write
  pattern: django.shortcuts.redirect <==> django.http.HttpResponseRedirect
because after my fix, your equivalence would not apply at all on the pattern. It's because in equivalence mode, the thing must match exactly, so foo(...) ==> bar(...) should get applied only when the user wrote foo(...) in his pattern; if he wrote foo(...,$X) it should not apply. If you want it to apply, we need to extend a few things, like having metavariable for multiple arguments.

**Comment by minusworld** [comment] 2020-05-22 16:26
OK, that makes sense! Thanks @aryx!

**Comment by brendongo** [comment] 2020-05-27 21:41
https://semgrep.live/Qrg4?version=0.8.1 with @aryx's suggestion for convenience

**Comment by dlukeomalley** [comment] 2021-08-05 17:38
Closing as this feature has been deprecated.

**Closed as completed by dlukeomalley** 2021-08-05 17:38 UTC
Labels: bug, pattern:equivalence, alpha
