### ISSUE TITLE
Inline // nosem not working

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#2033] opened 2020-11-12 18:43 UTC
**Describe the bug**
When chef runs Semgrep in CI, they have several lines that get flagged every time, even though they are tagged with comments like // nosem: ruleid

**To Reproduce**
Create a file in go that violates the rule go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection and add a // nosem: go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection to it. Then run semgrep 

**Expected behavior**
This line of code should not show up in Semgrep findings on the commandline

**What is the priority of the bug to you?**
P2 - this was a P0 for msorens, but since // nosem without rule id specified seems to work, he is unblocked now. Others may still become blocked, too, though.

**Environment**
Docker using custom Buildkite setup
Language: Go

**Comment by mschwager** [comment] 2020-11-12 21:37
It works for me here: https://semgrep.dev/s/B2BA/

I also tested this out locally and it worked there too. :thinking:

**Comment by msorens** [comment] 2020-11-13 03:30
@mschwager Could you post details of how you tested from the command line locally. It is not working for me and I am seeing some new unusual behavior--it is putting my entire file path in the rule id on the first line here!
```
severity:error rule:Users.msorens.code.go.src.github.com.chef.automate.semgrep.grpc-client-insecure-connection: Found an insecure gRPC connection. This creates a connection without encryption to a gRPC server. A malicious attacker could tamper with the gRPC message, which could compromise the machine.
10:    conn, err := grpc.Dial(address, grpc.WithInsecure()) // nosem: grpc-client-insecure-connection
```

**Comment by mschwager** [comment] 2020-11-13 14:13
By default the `nosem` functionality requires the full rule-id, e.g.

```
// nosem: Users.msorens.code.go.src.github.com.chef.automate.semgrep.grpc-client-insecure-connection
```

You can disable this functionality with the `--no-rewrite-rule-ids` flag, which will allow:

```
// nosem: grpc-client-insecure-connection
```

**Comment by msorens** [comment] 2020-11-13 18:29
OK, let's back up a bit. Here are the details of my particular issue.

I have in my file this bit of code:
```
func conn() grpc.ClientConnInterface {
	cc, err := grpc.Dial("localhost:1234", grpc.WithInsecure()) // nosem: go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
	if err != nil {
		panic(err)
	}
	return cc
}
```

In my CI pipeline I am invoking semgrep-agent...
```
python -m semgrep_agent --publish-token "\$SEMGREP_TOKEN" --publish-deployment \$SEMGREP_ID
```
That uses a policy consisting of a single ruleset, `r2c-ci`, which contains the rule mentioned in my `nosem` above.

The result in CI is this:
```
    === detecting environment
| versions    - semgrep 0.30.0 on Python 3.7.9
| environment - running in git, triggering event is 'unknown'
| semgrep.dev - logged in as deployment #48
=== setting up agent configuration
| using semgrep rules configured on the web UI
| using path ignore rules from .semgrepignore
| found 504 files in the paths to be scanned
| skipping 64 files based on path ignore rules
=== looking for current issues in 440 files
| 3 current issues found
go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
     > entitlement/cmd/entitlement-service/client.go:135
     ╷
  135│   cc, err := grpc.Dial("localhost:4841", grpc.WithInsecure()) // nosem: go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
```

... plus two more similar issues; all three should be suppressed via those `nosem` comments.

Interestingly when I run `semgrep -f p/r2c-ci` locally it is working correctly--the item is not flagged. The only difference I am aware of is semgrep version (locally 0.31.1 compared to 0.30.0 used by semgrep-agent at the moment).

**Comment by msorens** [comment] 2020-11-13 18:47
Oh, one more thing, @mschwager . If I change the `nosem` comment to omit the target (that is, just `// nosem`) that the system functions correctly; those three issues are not reported.

**Comment by mschwager** [comment] 2020-11-13 19:25
Hmm, weird. I'm unable to reproduce with nearly the same setup.

Trying against:

```go
func conn() grpc.ClientConnInterface {
	cc, err := grpc.Dial("localhost:1234", grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	return cc
}
```

```
$ python -m semgrep_agent --config p/r2c-ci 
=== detecting environment
| versions    - semgrep 0.30.0 on Python 3.7.0
| environment - running in git, triggering event is 'unknown'
| semgrep.dev - not logged in
=== setting up agent configuration
| using semgrep rules from p/r2c-ci
| using default path ignore rules of common test and dependency directories
| found 5 files in the paths to be scanned
| skipping 1 file based on path ignore rules
=== looking for current issues in 4 files
| 1 current issue found
go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
     > test.go:2
     ╷
    2│   cc, err := grpc.Dial("localhost:1234", grpc.WithInsecure())
     ╵
     = Found an insecure gRPC connection. This creates a connection without
       encryption to a gRPC server. A malicious attacker could tamper with the
       gRPC message, which could compromise the machine.

=== exiting with failing status
```

If I include the `nosem` comment:

```go
func conn() grpc.ClientConnInterface {
	cc, err := grpc.Dial("localhost:1234", grpc.WithInsecure()) // nosem: go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
	if err != nil {
		panic(err)
	}
	return cc
}
```

```
$ python -m semgrep_agent --config p/r2c-ci 
=== detecting environment
| versions    - semgrep 0.30.0 on Python 3.7.0
| environment - running in git, triggering event is 'unknown'
| semgrep.dev - not logged in
=== setting up agent configuration
| using semgrep rules from p/r2c-ci
| using default path ignore rules of common test and dependency directories
| found 5 files in the paths to be scanned
| skipping 1 file based on path ignore rules
=== looking for current issues in 4 files
| No current issues found
=== not looking at pre-existing issues since there are no current issues
=== exiting with success status
```

The only difference I see in our setups are: 1.) we're not using the same Python version, `3.7.0` vs. `3.7.9`, and 2.) our local git states could be different, but I wouldn't expect that to affect this. To your knowledge, am I correctly reproducing?

cc @underyx who may understand this better.

**Comment by underyx** [comment] 2020-11-13 19:27
@minusworld could you check the rule IDs when using a semgrep.dev policy? I think they might be different and including the /tmp/…/ path we download the rules to.

**Comment by underyx** [comment] 2020-11-13 19:28
But I also thought I saw @chmccreery fixing that here: https://github.com/returntocorp/semgrep-action/commit/0b39727b2839ce7a38dc1a08a0991c566183d8b8#diff-c8c6d93c56ca3e3dbc740822fa786917478a112a4d6ed6eb7bb3667f225f6877R131

**Comment by msorens** [comment] 2020-11-14 00:12
@underyx FWIW: Yes, in CI I used to see the `tmp.` artifact you mentioned--but yielding exactly the same end result. That is, it used to show this:
```
| 3 current issues found
tmp.go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
. . .
```
but is now showing this:
```
| 3 current issues found
go.grpc.security.grpc-client-insecure-connection.grpc-client-insecure-connection
. . .
```

**Comment by underyx** [comment] 2020-11-14 00:56
I see, thanks for confirming that @msorens! Looking at @chmccreery's commit, seems like we only strip the `tmp.` when printing the rule ID, so `semgrep` thinks that is actually part of the proper rule ID, and that must be why the `// nosem` comment that seems logical doesn't actually work. It expects the `tmp.[…]` rule ID to be mentioned in the comment.

@minusworld @mschwager are you maybe familiar with where this should be fixed? Is this what `--no-rewrite-rule-ids` circumvents?

**Comment by chmccreery** [comment] 2020-11-16 19:08
Ohh yes, I looked into stripping the temporary folder name earlier in the pipeline with @nbrahms but it got really hairy. If that is what needs to happen, we can revisit it, but if Semgrep core can handle this, that would likely be preferable

**Comment by mschwager** [comment] 2020-11-16 21:08
> Is this what `--no-rewrite-rule-ids` circumvents?

Yes, I believe it should. But it also comes with its own trade-offs. I'm not 100% sure, but I believe rule-id rewriting and `--no-rewrite-rule-ids` were originally included to prevent rule-id duplication (e.g. `sql-injection` rule-id in Python and Ruby won't stomp on each other). So using that flag to turn it off opens the door for some issues there. I've touched on this in a bit more depth previously: https://r2c.quip.com/hIbYAewnv8Er/Extended-Internal-Dry-run#JAXACAFRZSD.

For now I think our options are:

1. Pay down the big cost of moving toward a different rule-id scheme.
2. Find a good band-aid solution that will support us until we can do (1).
3. Other? Can we simply enable `--no-rewrite-rule-ids` and be fine? Will this play well with the cloud app (i.e. linking rules to their rule-id)?

I'd lean toward (2) for now. @underyx @chmccreery is there anyway we can patch over this until we have a better solution?

EDIT: After rereading @underyx's comment:

> ... seems like we only strip the `tmp.` when printing the rule ID, so semgrep thinks that is actually part of the proper rule ID ...

Another option would be to strip the `tmp.` in the internal representation, not just the output. Is that a good (2) solution?

**Comment by chmccreery** [comment] 2020-11-16 21:54
@mschwager I am happy to try stripping the `tmp.` as you suggest. I think I tried to do that before and it ran into issues, but I can't remember what they were and I'm happy to take another look now to resolve this issue.

**Comment by msorens** [comment] 2020-11-17 16:07
Thanks for the efforts going into resolving this! I was just wondering what the full scope of this is. From my (limited) perspective--this has been a problem for different rules in different repos for me--it appears that I cannot use a targeted nosem (i.e., `//nosem: <rule-id>`) at all. Are there any scenarios where a targeted nosem does work today? Some other language, perhaps...? Is there something peculiar about what I am doing?

**Comment by mschwager** [comment] 2020-11-17 18:22
Hey @msorens we found the bug on our end. Due to the way we manage rules in `semgrep-agent`, we were mismatching rule-id's in output vs. their internal representation. This meant that `nosem` functionality was breaking when specifying a rule-id. This will be fixed with https://github.com/returntocorp/semgrep-action/pull/109 :+1:

**Closed as completed** 2020-11-17 18:48 UTC
Labels: bug

**Comment by mschwager** [comment] 2020-11-17 21:58
@msorens can you confirm that the latest `semgrep-agent` fixes this for you?

**Comment by msorens** [comment] 2020-11-17 22:19
Testing methodology:

1. **Establish baseline.** Removed `nosem` masking entirely -- confirmed issues **are** flagged. ✅ 

2. **Test issue at hand.** Re-introduced targeted `nosem` (i.e. `// nosem: <rule-id>`) on previously tagged lines -- confirmed issues are **not** flagged. ✅ 

3. **Avoid phantom results.** Since I have returned the state to what existed before this PR, it is possible that semgrep-agent would consider those lines unchanged and not flag them (even if a virgin run would have). So I added a completely new line with a targeted `nosem` tag -- confirmed issues are **not** flagged. ✅ 

4. **Genericize results.** Introduce targeted `nosem` in another language file (`3 == 3 // nosem: python.lang.correctness.useless-eqeq.useless-eqeq`)  -- confirmed issue flagged without the `nosem` ✅  and not flagged with the `nosem`. ✅ 

_Footnote: If you are interested in my thoughts about phantom tests, see my exposition in [The Phantom Menace in Unit Testing](https://www.red-gate.com/simple-talk/dotnet/software-testing/the-phantom-menace-in-unit-testing/)._

**Comment by chmccreery** [comment] 2020-11-17 23:08
Beautiful 🙏 👏
