### ISSUE TITLE
Semgrep doesn't respect ignores if `--sarif` argument is used

### ISSUE THREAD

**Issue by JorTurFer** [semgrep/semgrep#7121] opened 2023-02-10 17:46 UTC
**Describe the bug**
if I execute `semgrep ci` the ignores in the code are respected and I can set all the rules as blockers (which is useful for PRs) but we want to upload the sarif report to GH Security, so we need to use `semgrep ci --sarif --output=semgrep.sarif` , once I set `--sarif`  the `// nosemgrep:` comments are ignored, failing the CI

**To Reproduce**
Write a code with any issue, ignore the issue with `// nosemgrep:` and execute `semgrep ci --sarif --output=semgrep.sarif``, you will see that the ignored issue is detected even thought it's ignored.

**Expected behavior**
I expect that `// nosemgrep:` comments are respected, even if I'm generating sarif report

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
We use semgrep GH action

**Use case**
We have a GH Action workflow to validate PRs and pushes into main. Due to this, we would like to set all rules as blockers, but if we do it, this problem related with sarif makes it fail. If this works, we can set all the rules as blockers

**Comment by JorTurFer** [comment] 2023-02-26 01:36
Any update?

**Comment by JorTurFer** [comment] 2023-03-07 21:40
Hello,
Do you have any roadmap or update where we check the progress? This isn't a blocker but it's annoying because we cannot use all the rules as blocker because we have some ignores

**Comment by mknet3** [comment] 2023-03-27 21:37
Hi! Same issue here... are there any news? 🙏

**Comment by xoanmm** [comment] 2023-03-27 21:41
we need this feature too, do you have any news?

**Comment by StefanFl** [comment] 2023-04-12 20:02
It would be great if this could be fixed.

**Comment by StefanFl** [comment] 2023-04-16 06:58
~~I had another look at the SARIF output of Semgrep. If a line in the source code is marked with `nosemgrep`, the result contains~~

```json
          "suppressions": [
            {
              "kind": "inSource"
            }
          ]
```

~~In my view this is the correct way to deal with it and so I would not treat it as a bug of Semgrep.~~

The SARIF file is fine, but the issue is about the exit code of Semgrep.

**Comment by JorTurFer** [comment] 2023-04-16 08:15
Hi @StefanFl ,
The sarif file is correct, but despite of the file is correct and it contains the ignores, the command execution returns an error.

In our case, this is a blocker because the the command should fail only when there are broken rules. If there is a ignore comment, the rule isn't broken.

My issue referred to the command execution itself and not to sarif file, as we want to enable the rules as blocker, but semgrep execution is not respecting the ignores and failing despite of them.

**Comment by StefanFl** [comment] 2023-04-16 15:57
Hi @JorTurFer, sorry, I should have read your issue more carefully. Marked my previous comments accordingly.

**Comment by dttung2905** [comment] 2023-05-13 14:00
Hi team, is there any update on this issue? I have also face the same problem unfortunately :sweat_smile:

**Comment by ievans** [comment] 2023-05-14 18:58
I suspect this will probably be fixed in the osemgrep port (no near-term ETA), but we would welcome a test case and PR for it in the meantime.

**Comment by ievans** [comment] 2023-05-14 18:59
CC @aryx who may have a better idea on timelines

**Comment by tghosth** [comment] 2023-06-27 13:15
@ievans this isn't a great test case but I created this:

https://github.com/tghosth/nosemgrep_test/actions

Basically, if semgrep is working correctly then both these actions should be green because any violations are marked by "nosemgrep".

Currently, the "Sarif" Action is failing because --sarif does not respect nosemgrep.

Just spent a good couple of hours trying to figure out why this wasn't working 😭😭😭😭

**Comment by sim642** [comment] 2023-07-25 17:36
This is extremely annoying. Here's it flagging precisely the things it's supposed to be ignoring: https://github.com/goblint/analyzer/pull/1117#pullrequestreview-1545946072.

**Comment by bmahe** [comment] 2023-08-02 01:45
I just noticed this issue after opening #8411.
Since #8411 contains more details and a potential way to fix it, I will close this one.

**Closed as completed by bmahe** 2023-08-02 01:45 UTC
Labels: bug, priority:medium, feature:ignore

**Comment by JorTurFer** [comment] 2023-08-02 06:34
Don't worry, I'll follow the new issue :)
