### ISSUE TITLE
UX for multiple matches: need visual separation cue

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1990] opened 2020-11-09 22:29 UTC
**Is your feature request related to a problem? Please describe.**
When semgrep reports multiple issues in a single file it is not at all obvious. The first couple times I did not even realize they were separate issues. The only way to tell is to notice discontinuities in the line numbers. Need to be much more obvious than that.

**Describe the solution you'd like**
Add a visual cue separating contexts of each occurrence; perhaps with (a) just a line (some hyphens) as shown, or (b) even just repeat the file name/header.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/6817500/98603704-5f58e700-2297-11eb-8cf6-3d05a4198be2.png">

My preference would be (a) because currently the visual cues to see file boundaries are very clear. If you repeat the file name/header then it will be much less obvious that several contiguous items are actually in the same file.

**Additional context**
semgrep 0.30.0

**Comment by dlukeomalley** [comment] 2020-11-10 01:33
I believe this is a duplicate of https://github.com/returntocorp/semgrep/issues/1866. I'd favor this ticket over the other due to its greater detail 👍

**Comment by dlukeomalley** [comment] 2020-12-08 17:57
Closing as fixed by #2082

**Closed as completed by dlukeomalley** 2020-12-08 17:57 UTC
Labels: enhancement, user:external, fixed, feature:cli-output
